In [11]:
from pathlib import Path

import pandas as pd
from IPython.display import Markdown, display

csv_directory = Path("MCZ-1564")
if not csv_directory.exists():
    csv_directory = Path(".")

user_data_df = pd.read_csv(csv_directory / "user_data.csv")
user_activity_df = pd.read_csv(csv_directory / "user_acitivy.csv")

In [12]:
display(Markdown("### user_data_df"))
print(user_data_df.shape[0])
display(user_data_df.head(10))

display(Markdown("### user_activity_df"))
print(user_activity_df.shape[0])
display(user_activity_df.head(10))

### user_data_df

84573

,user_id,resume_created_at,resume_text,work_experience_text,education_text,noteworthy_information,mission_statement,position_types,organization_text,work_environments,degrees,board_certifications,location_preference_text,experience_years,certification_text,publication_text
0,20695,2026-05-23 14:05:26+00,"\n\n CURRICULUM VITAE\n Raed Hattab, MD\n 50 N...",organization_name: Arthritis\noccupation: \noc...,education_level: \nschool_name: Harvard Medica...,\n\n\n\n\n,NaN,"Full-Time, Locums/Travel, Part-Time/Contract","organization_name: AMA, AAPM&R\njoin_month: \n...","Academic/Training Program, Ambulatory Surgery ...","MD/DO, Residency/Fellowship/Externship",BE/BC,country: United States\nstate: Florida\ncity:,20.0,certification: \n\n--- next certification ---\...,NaN
1,20787,2021-08-12 14:44:39+00,NaN,NaN,NaN,\n,NaN,Full-Time,organization_name: American Medical Associatio...,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: Maryland\ncity: \n\n--- next...,0.0,NaN,NaN
2,20914,2026-03-11 23:08:02+00,NaN,NaN,education_level: \nschool_name: Tulane Medical...,\n\n,NaN,Full-Time,NaN,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: California\ncity: \n\n--- ne...,0.0,NaN,NaN
3,20940,2025-04-24 00:07:08+00,"\n9961 East South Bend Drive\n\nScottsdale, AZ...",NaN,NaN,\n,NaN,Locums/Travel,organization_name: AMA\njoin_month: \njoin_yea...,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: Arizona\ncity:,0.0,certification: \n\n--- next certification ---\...,NaN
4,21028,2025-04-27 00:17:38+00,\n Luis M. Quinon...,organization_name: Kinder Pediatric Urgent Car...,education_level: \nschool_name: Lincoln Medica...,"\nSpeaks Spanish, Portuguese.",NaN,Full-Time,organization_name: Union City Volunteer Ambula...,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: New Jersey\ncity: \n\n--- ne...,0.0,certification: \n\n--- next certification ---\...,NaN
5,21115,2024-11-05 03:04:00+00,"KEITH S. GOLDSTEIN, MD, MPH, FAAFP, DABPM\nBoa...",NaN,NaN,NaN,NaN,Full-Time,"organization_name: AMA, Pennsylvania Med Soc, ...","Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: Florida\ncity:,0.0,NaN,NaN
6,21140,2019-03-21 17:05:25+00,"\n \nNasrin\n \nAnsari, M.D.\n \nFACS\n \n \n...",NaN,education_level: Residency\nschool_name: SUNY-...,\n,NaN,Full-Time,NaN,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: Virginia\ncity: \n\n--- next...,0.0,NaN,NaN
7,21173,2025-05-26 01:24:43+00,Adam G. Field MD Personal Information Place of...,NaN,NaN,\n,NaN,"Full-Time, Locums/Travel, Part-Time/Contract",NaN,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: California\ncity:,0.0,NaN,NaN
8,21218,2024-09-11 23:53:52+00,\n JAMES R. DAVI...,organization_name: Marshfield Clinic\noccupati...,education_level: \nschool_name: University of ...,Dermatopathology\r\nAP/CP\n,NaN,Full-Time,organization_name: ASDP\njoin_month: \njoin_ye...,"Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: Wyoming\ncity: \n\n--- next ...,0.0,certification: \n\n--- next certification ---\...,NaN
9,21242,2022-03-17 12:31:29+00,...,organization_name: Guam Memorial Hospital Auth...,education_level: Residency\nschool_name: Unive...,\n\n\n\n,NaN,Full-Time,"organization_name: RSNA, ACR, ABR, ASSR, ASNR\...","Academic/Training Program, Ambulatory Surgery ...",MD/DO,BE/BC,country: \nstate: Hawaii\ncity: \n\n--- next l...,0.0,certification: \n\n--- next certification ---\...,NaN

### user_activity_df

1045066

,npi_number,npi_verification_status,user_id,first_name,last_name,occupation,specialties,registration_date,last_activity_date,last_login_date,...,sms_stop_message_count,email_click_count,sms_click_count,job_match_unsubscribe_clicks_count,company_email_unsubscribe_click_count,other_unsubscribe_click_count,email_open_count,saved_search_subscribed_count,message_alert_subscribed_count,saved_search_unsubscribed_count
0,1497701718,verified,20695,Raed,Hattab,Physician,"Pain Management, Physiatry/Physical Medicine &...",2004-10-18 05:00:00+00,2026-05-27,2026-05-26,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,1497701718,verified,20695,Raed,Hattab,Physician,"Pain Management, Physiatry/Physical Medicine &...",2004-10-18 05:00:00+00,2026-05-27,2026-05-26,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
2,1497701718,verified,20695,Raed,Hattab,Physician,"Pain Management, Physiatry/Physical Medicine &...",2004-10-18 05:00:00+00,2026-05-27,2026-05-26,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
3,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,2.0,NaN,NaN,NaN
5,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,7.0,NaN,NaN,NaN
6,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,3.0,NaN,NaN,NaN
7,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,6.0,NaN,NaN,NaN
8,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,2.0,NaN,NaN,NaN
9,1063579753,verified,20787,Hugh,Wilkinson,Physician,Obstetrics & Gynecology,2004-11-10 06:00:00+00,2026-05-24,2026-05-24,...,0,0,0,0,0,0,2.0,NaN,NaN,NaN

In [22]:
values = set(user_activity_df["specialties"].tolist())

print(len(values))
print(values)

6229