In [1]:
import pandas as pd

In [2]:
df_json = pd.read_json('./distinct_taxonomy_codes_missing_specialty.json')

In [3]:
df_json

                                           taxonomy_code
0                                         ["101Y00000X"]
1                                         ["183500000X"]
2                                         ["101YM0800X"]
3                                         ["3747P1801X"]
4                                         ["2255A2300X"]
...                                                  ...
20037                       ["101YA0400X", "376J00000X"]
20038  ["163WM0102X", "163WC0400X", "163WP0200X", "16...
20039         ["251E00000X", "374U00000X", "164W00000X"]
20040  ["261QM1300X", "202D00000X", "374K00000X", "22...
20041  ["164W00000X", "164X00000X", "104100000X", "31...

[20042 rows x 1 columns]

In [33]:
from ast import literal_eval

df_json["taxonomy_list"] = df_json["taxonomy_code"].apply(lambda x: literal_eval(x))

In [34]:
df_json["taxonomy_list"]

0                                             [101Y00000X]
1                                             [183500000X]
2                                             [101YM0800X]
3                                             [3747P1801X]
4                                             [2255A2300X]
5                                             [225700000X]
6                                             [224Z00000X]
7                                             [174N00000X]
8                                             [171W00000X]
9                                             [126800000X]
10                                            [103K00000X]
11                                            [225200000X]
12                                            [374J00000X]
13                                            [242T00000X]
14                                            [1223X0400X]
15                                            [1223P0106X]
16                                            [106H00000X]
17                                            [104100000X]
18                                [1835P0018X, 183500000X]
19                                            [163WG0000X]
20                    [163WP0808X, 163WC1500X, 163WM0102X]
21                                            [163WP2201X]
22                                            [163W00000X]
23                                            [163WC0200X]
24                                            [172V00000X]
25                                [104100000X, 101YA0400X]
26                                            [376K00000X]
27                                            [164W00000X]
28                                [101YA0400X, 101Y00000X]
29                                            [237700000X]
30                                            [101YA0400X]
31                                            [227900000X]
32                                [221700000X, 101YP2500X]
33                                            [164X00000X]
34                                            [251E00000X]
35       [374U00000X, 3747P1801X, 372600000X, 376J00000...
36                                            [146N00000X]
37                                            [163WG0100X]
38                                            [171M00000X]
39                                [347C00000X, 343900000X]
40                                            [2279G1100X]
41                                            [171100000X]
42                                [235500000X, 222Q00000X]
43                                            [320900000X]
44                                            [183700000X]
45                                            [374U00000X]
46                                            [332B00000X]
47                                            [163WS0200X]
48                                [163W00000X, 163WH0200X]
49                                            [2355S0801X]
50                                            [253Z00000X]
51                                            [310400000X]
52                                [171M00000X, 164W00000X]
53                                            [343900000X]
54                                            [101YP2500X]
55                                [106H00000X, 225400000X]
56                                            [1223P0300X]
57                    [101YM0800X, 101YA0400X, 101Y00000X]
58                                [101YP2500X, 101YA0400X]
59                                [374J00000X, 104100000X]
60                                [237700000X, 332S00000X]
61                                            [163WH0200X]
62                                            [224Y00000X]
63                                [101YP2500X, 101Y00000X]
64                                            [376J00000X]
65                                            [1041S0200X]
66                                [101YP2500X, 101YM0800X]
67                                            [225C00000X]
68                                            [163WP0808X]
69                                            [163WI0600X]
70                                            [246Z00000X]
71                                [104100000X, 163W00000X]
72                                            [174H00000X]
73                                            [322D00000X]
74                                            [163WD0400X]
75                                            [1835P1200X]
76                                            [224900000X]
77                                            [251B00000X]
78                                            [246ZE0600X]
79                                [246ZC0007X, 246ZS0410X]
80                                [1041S0200X, 171M00000X]
81                                            [1223E0200X]
82                                            [133N00000X]
83                                            [3747A0650X]
84                                [251S00000X, 171M00000X]
85                                            [163WP0809X]
86                                [246ZS0410X, 246ZC0007X]
87                                            [247100000X]
88                                            [376G00000X]
89                                [171M00000X, 172A00000X]
90                                            [247200000X]
91                                            [3336C0003X]
92                                [374U00000X, 3747P1801X]
93                                            [1710I1002X]
94                                            [175T00000X]
95                                            [225400000X]
96                                            [163WC0400X]
97                                            [170300000X]
98                                            [167G00000X]
99                                            [311ZA0620X]
100                   [101YP2500X, 101YM0800X, 101YA0400X]
101                                           [124Q00000X]
102                               [101YA0400X, 101YM0800X]
103                   [101YP2500X, 101Y00000X, 101YM0800X]
104                                           [1835P0018X]
105                                           [163WM0705X]
106                                           [1744P3200X]
107                                           [163WH1000X]
108                                           [225A00000X]
109                               [101YS0200X, 101Y00000X]
110                               [101Y00000X, 106H00000X]
111                               [101YA0400X, 101YP2500X]
112                               [101YM0800X, 106H00000X]
113                                           [176B00000X]
114                                           [163WC1500X]
115                               [183500000X, 1835P0018X]
116                               [101YM0800X, 101YA0400X]
117                               [103K00000X, 101YM0800X]
118                                           [163WA2000X]
119                               [171M00000X, 172V00000X]
120                               [372600000X, 376J00000X]
121                   [332B00000X, 1744P3200X, 335E00000X]
122                                           [251S00000X]
123                               [104100000X, 101Y00000X]
124                                           [172A00000X]
125                                           [222Q00000X]
126                                           [175F00000X]
127                               [163WE0003X, 146L00000X]
128                                           [246ZC0007X]
129                                           [282N00000X]
130                                           [163WX0601X]
131                               [101YM0800X, 374J00000X]
132                                           [163WI0500X]
133                                           [172M00000X]
134                   [101Y00000X, 101YA0400X, 101YP2500X]
135                                           [2470A2800X]
136                               [101YM0800X, 225400000X]
137                               [163W00000X, 176B00000X]
138                               [183500000X, 1835P2201X]
139                               [101YP2500X, 103K00000X]
140                                           [171400000X]
141                                           [103G00000X]
142                               [172V00000X, 3747P1801X]
143                               [101YM0800X, 101YP2500X]
144                               [171100000X, 163W00000X]
145                               [225A00000X, 2355S0801X]
146                                           [251J00000X]
147                                           [3416L0300X]
148                                           [261QM0850X]
149                                           [1223P0221X]
150                                           [314000000X]
151                               [222Q00000X, 103K00000X]
152                               [172V00000X, 175T00000X]
153                               [171M00000X, 101YP2500X]
154                                           [1710I1003X]
155                               [171M00000X, 225C00000X]
156                               [253J00000X, 101YM0800X]
157                               [104100000X, 171M00000X]
158      [3747A0650X, 372500000X, 372600000X, 3747P1801...
159                                           [2471M2300X]
160                                           [102L00000X]
161                   [163WM0705X, 163WG0000X, 163W00000X]
162                                           [261Q00000X]
163      [101YP2500X, 101YA0400X, 101YM0800X, 101Y00000...
164                                           [405300000X]
165                                           [374700000X]
166                               [101YM0800X, 103K00000X]
167                                           [261QP2000X]
168                   [101Y00000X, 101YA0400X, 101YM0800X]
169                               [174N00000X, 101YM0800X]
170                                           [252Y00000X]
171                                           [225CA2400X]
172                               [374U00000X, 225700000X]
173                                           [163WE0003X]
174                                           [133NN1002X]
175                                           [363A00000X]
176                               [103K00000X, 222Q00000X]
177                                           [146L00000X]
178                                           [1835P2201X]
179                               [163WC1500X, 163WG0000X]
180                                           [163WP0200X]
181                               [101YM0800X, 101Y00000X]
182                               [171M00000X, 251S00000X]
183                                           [251C00000X]
184                                           [163WR0006X]
185                   [101YM0800X, 101Y00000X, 106H00000X]
186                                           [1835P0200X]
187                               [163WP0808X, 164X00000X]
188                                           [373H00000X]
189                                           [156F00000X]
190                                           [163WG0600X]
191                               [103K00000X, 101YA0400X]
192                               [104100000X, 101YP2500X]
193                               [171M00000X, 225A00000X]
194                                           [171R00000X]
195                                           [246QM0706X]
196                               [101Y00000X, 101YM0800X]
197                                           [163WA0400X]
198                               [101YA0400X, 164W00000X]
199                               [101YS0200X, 101YP2500X]
200                                           [1223X2210X]
201                   [101YM0800X, 175T00000X, 101Y00000X]
202      [163WP0809X, 163WP0808X, 163WP0807X, 163WN0800...
203                   [171M00000X, 104100000X, 172V00000X]
204                               [175T00000X, 171M00000X]
205                               [1041S0200X, 104100000X]
206                               [104100000X, 1041S0200X]
207                               [101YM0800X, 104100000X]
208                               [104100000X, 172V00000X]
209                               [103K00000X, 101Y00000X]
210                                           [284300000X]
211                                           [163WR0400X]
212                               [171M00000X, 101YA0400X]
213      [372500000X, 3747P1801X, 376J00000X, 372600000...
214                               [101YA0400X, 106H00000X]
215                                           [311Z00000X]
216                               [101YP1600X, 101Y00000X]
217                               [175F00000X, 225700000X]
218                   [101YM0800X, 101Y00000X, 101YP2500X]
219                               [173C00000X, 225700000X]
220                                           [332S00000X]
221                               [225400000X, 104100000X]
222                                           [175M00000X]
223                                           [174M00000X]
224       [101YS0200X, 101YM0800X, 101YP2500X, 101Y00000X]
225      [251C00000X, 376J00000X, 253Z00000X, 343900000...
226                                           [163WP0807X]
227                                           [335E00000X]
228       [372500000X, 376J00000X, 3747P1801X, 3747A0650X]
229                               [253Z00000X, 251E00000X]
230                               [175F00000X, 133NN1002X]
231                               [106H00000X, 101YM0800X]
232                                           [225000000X]
233                               [247200000X, 103K00000X]
234                               [172V00000X, 106H00000X]
235                               [171M00000X, 175T00000X]
236                               [163W00000X, 101Y00000X]
237      [372600000X, 376J00000X, 3747A0650X, 372500000...
238                                           [177F00000X]
239                                           [122400000X]
240      [372600000X, 3747P1801X, 3747A0650X, 376J00000...
241                                           [221700000X]
242      [101YP2500X, 171400000X, 101Y00000X, 101YA0400...
243                                           [291U00000X]
244                               [104100000X, 103K00000X]
245                                           [261QC1500X]
246                               [1835P0018X, 1835P1200X]
247                                           [2279E0002X]
248                                           [237600000X]
249                                           [305R00000X]
250                                           [101YS0200X]
251                               [101YP2500X, 106H00000X]
252                   [1835G0303X, 183500000X, 1835P1200X]
253                                           [247000000X]
254                               [251S00000X, 101YM0800X]
255                                           [171000000X]
256                               [171M00000X, 104100000X]
257                   [3747P1801X, 3747A0650X, 374U00000X]
258                               [174H00000X, 101YM0800X]
259                               [101Y00000X, 101YP2500X]
260                               [163WP0808X, 101YP2500X]
261                               [101YM0800X, 171M00000X]
262                                           [372500000X]
263                               [171M00000X, 101YM0800X]
264                               [101YA0400X, 171M00000X]
265                               [101Y00000X, 164X00000X]
266                               [374J00000X, 171100000X]
267                   [101Y00000X, 101YM0800X, 101YP2500X]
268                   [103K00000X, 171M00000X, 104100000X]
269                                           [163WX0200X]
270                                           [261QM0801X]
271                               [376K00000X, 172V00000X]
272      [372500000X, 376J00000X, 372600000X, 3747P1801...
273                                           [2279H0200X]
274                               [3747P1801X, 175T00000X]
275                               [172V00000X, 163WE0003X]
276                   [2255A2300X, 146N00000X, 174H00000X]
277                                           [342000000X]
278                               [101Y00000X, 101YA0400X]
279                                           [163WL0100X]
280       [101YM0800X, 171M00000X, 106H00000X, 101Y00000X]
281                   [174H00000X, 164W00000X, 163WH0200X]
282                   [101YA0400X, 101YM0800X, 171M00000X]
283                               [172V00000X, 171M00000X]
284                                           [1223P0700X]
285                   [171M00000X, 172V00000X, 251S00000X]
286                                           [2279C0205X]
287                               [374J00000X, 172V00000X]
288                   [174H00000X, 374J00000X, 174N00000X]
289                   [101YM0800X, 101YP2500X, 101Y00000X]
290                                           [173C00000X]
291                               [163WC1500X, 163W00000X]
292      [3747P1801X, 372600000X, 372500000X, 3747A0650...
293                               [164W00000X, 163W00000X]
294                               [106H00000X, 101YP2500X]
295                   [101YP2500X, 101YA0400X, 101YM0800X]
296                   [171M00000X, 103K00000X, 104100000X]
297                                           [347C00000X]
298                               [163WM0705X, 163W00000X]
299                                           [372600000X]
300                   [252Y00000X, 101YP2500X, 101YM0800X]
301                               [175T00000X, 101Y00000X]
302                               [103K00000X, 101YP2500X]
303                                           [227800000X]
304                                           [2471C3402X]
305                   [225700000X, 171100000X, 175F00000X]
306                                           [2471S1302X]
307                               [227800000X, 163W00000X]
308                               [172V00000X, 101Y00000X]
309                                           [224L00000X]
310                                           [175L00000X]
311                               [171M00000X, 251B00000X]
312      [3747A0650X, 372600000X, 376J00000X, 372500000...
313                                           [246QC1000X]
314                                           [226000000X]
315                                           [246ZS0410X]
316                   [101YP2500X, 101YA0400X, 101Y00000X]
317                               [101YP2500X, 225A00000X]
318                               [164W00000X, 225700000X]
319                                           [246RP1900X]
320                               [101YA0400X, 104100000X]
321                               [225A00000X, 101Y00000X]
322                               [163W00000X, 163WC0400X]
323                               [101YM0800X, 101YS0200X]
324                   [171M00000X, 101Y00000X, 251S00000X]
325                                           [163WC1400X]
326                   [101YM0800X, 101YA0400X, 106H00000X]
327                                           [1835G0303X]
328                                           [125J00000X]
329                                           [2255R0406X]
330                               [172V00000X, 224Z00000X]
331                                           [163WM1400X]
332       [3747P1801X, 372600000X, 372500000X, 376J00000X]
333                               [163WP0200X, 163WL0100X]
334                   [163WP0808X, 163WC0400X, 163W00000X]
335                                           [2278C0205X]
336                               [1835C0206X, 183500000X]
337                               [104100000X, 101YM0800X]

In [35]:
# flatten taxonomy_list to have just the unique taxonomy codes
unique_taxonomy_codes = set()

for codes in df_json["taxonomy_list"]:
    unique_taxonomy_codes.update(codes)

In [7]:
unique_taxonomy_codes

{'101200000X',
 '101Y00000X',
 '101YA0400X',
 '101YM0800X',
 '101YP1600X',
 '101YP2500X',
 '101YS0200X',
 '102L00000X',
 '102X00000X',
 '103G00000X',
 '103K00000X',
 '104100000X',
 '1041S0200X',
 '106H00000X',
 '1223D0001X',
 '1223D0004X',
 '1223E0200X',
 '1223P0106X',
 '1223P0221X',
 '1223P0300X',
 '1223P0700X',
 '1223X0008X',
 '1223X0400X',
 '1223X2210X',
 '122400000X',
 '124Q00000X',
 '125J00000X',
 '125K00000X',
 '125Q00000X',
 '126800000X',
 '126900000X',
 '132700000X',
 '133N00000X',
 '133NN1002X',
 '136A00000X',
 '146D00000X',
 '146L00000X',
 '146M00000X',
 '146N00000X',
 '156F00000X',
 '156FC0800X',
 '156FC0801X',
 '156FX1100X',
 '156FX1101X',
 '156FX1201X',
 '156FX1202X',
 '156FX1900X',
 '163W00000X',
 '163WA0400X',
 '163WA2000X',
 '163WC0200X',
 '163WC0400X',
 '163WC1400X',
 '163WC1500X',
 '163WC1600X',
 '163WC2100X',
 '163WD0400X',
 '163WD1100X',
 '163WE0003X',
 '163WE0900X',
 '163WF0300X',
 '163WG0000X',
 '163WG0100X',
 '163WG0600X',
 '163WH0200X',
 '163WH0500X',
 '163WH1000X',
 '163WI0500X',
 '163WI0600X',
 '163WL0100X',
 '163WM0102X',
 '163WM0705X',
 '163WM1400X',
 '163WN0002X',
 '163WN0003X',
 '163WN0300X',
 '163WN0800X',
 '163WN1003X',
 '163WP0000X',
 '163WP0200X',
 '163WP0218X',
 '163WP0807X',
 '163WP0808X',
 '163WP0809X',
 '163WP1700X',
 '163WP2201X',
 '163WR0006X',
 '163WR0400X',
 '163WR1000X',
 '163WS0121X',
 '163WS0200X',
 '163WU0100X',
 '163WW0000X',
 '163WW0101X',
 '163WX0002X',
 '163WX0003X',
 '163WX0106X',
 '163WX0200X',
 '163WX0601X',
 '163WX0800X',
 '163WX1100X',
 '163WX1500X',
 '164W00000X',
 '164X00000X',
 '167G00000X',
 '170100000X',
 '170300000X',
 '171000000X',
 '1710I1002X',
 '1710I1003X',
 '171100000X',
 '171400000X',
 '171M00000X',
 '171R00000X',
 '171W00000X',
 '171WH0202X',
 '171WV0202X',
 '172A00000X',
 '172M00000X',
 '172P00000X',
 '172V00000X',
 '173000000X',
 '173C00000X',
 '173F00000X',
 '174200000X',
 '1744G0900X',
 '1744P3200X',
 '1744R1102X',
 '1744R1103X',
 '174H00000X',
 '174M00000X',
 '174MM1900X',
 '174N00000X',
 '174V00000X',
 '175F00000X',
 '175L00000X',
 '175M00000X',
 '175T00000X',
 '176B00000X',
 '176P00000X',
 '177F00000X',
 '183500000X',
 '1835C0205X',
 '1835C0206X',
 '1835C0207X',
 '1835E0208X',
 '1835G0303X',
 '1835I0206X',
 '1835N0905X',
 '1835N1003X',
 '1835P0018X',
 '1835P0200X',
 '1835P1200X',
 '1835P1300X',
 '1835P2201X',
 '1835S0206X',
 '1835X0200X',
 '183700000X',
 '193200000X',
 '193400000X',
 '202C00000X',
 '202D00000X',
 '202K00000X',
 '204R00000X',
 '207RH0005X',
 '207SC0300X',
 '207SG0207X',
 '207VC0300X',
 '2085B0100X',
 '2085H0002X',
 '2085R0203X',
 '208U00000X',
 '208VP0000X',
 '209800000X',
 '211D00000X',
 '221700000X',
 '222Q00000X',
 '224900000X',
 '224L00000X',
 '224Y00000X',
 '224Z00000X',
 '224ZE0001X',
 '224ZF0002X',
 '224ZL0004X',
 '224ZR0403X',
 '225000000X',
 '225200000X',
 '225400000X',
 '225500000X',
 '2255A2300X',
 '2255R0406X',
 '225600000X',
 '225700000X',
 '225800000X',
 '225A00000X',
 '225B00000X',
 '225C00000X',
 '225CA2400X',
 '225CA2500X',
 '225CX0006X',
 '226000000X',
 '226300000X',
 '227800000X',
 '2278C0205X',
 '2278E0002X',
 '2278E1000X',
 '2278G0305X',
 '2278G1100X',
 '2278H0200X',
 '2278P1004X',
 '2278P1005X',
 '2278P1006X',
 '2278P3800X',
 '2278P3900X',
 '2278P4000X',
 '2278S1500X',
 '227900000X',
 '2279C0205X',
 '2279E0002X',
 '2279E1000X',
 '2279G0305X',
 '2279G1100X',
 '2279H0200X',
 '2279P1004X',
 '2279P1005X',
 '2279P1006X',
 '2279P3800X',
 '2279P3900X',
 '2279P4000X',
 '2279S1500X',
 '235500000X',
 '2355A2700X',
 '2355S0801X',
 '237600000X',
 '237700000X',
 '242T00000X',
 '243U00000X',
 '246Q00000X',
 '246QB0000X',
 '246QC1000X',
 '246QC2700X',
 '246QH0000X',
 '246QH0401X',
 '246QH0600X',
 '246QI0000X',
 '246QL0900X',
 '246QL0901X',
 '246QM0706X',
 '246QM0900X',
 '246R00000X',
 '246RH0600X',
 '246RM2200X',
 '246RP1900X',
 '246W00000X',
 '246X00000X',
 '246XC2901X',
 '246XC2903X',
 '246XS1301X',
 '246Y00000X',
 '246YC3301X',
 '246YC3302X',
 '246YR1600X',
 '246Z00000X',
 '246ZA2600X',
 '246ZB0301X',
 '246ZB0302X',
 '246ZB0500X',
 '246ZB0600X',
 '246ZC0007X',
 '246ZE0500X',
 '246ZE0600X',
 '246ZG0701X',
 '246ZG1000X',
 '246ZI1000X',
 '246ZN0300X',
 '246ZS0410X',
 '246ZX2200X',
 '247000000X',
 '2470A2800X',
 '247100000X',
 '2471B0102X',
 '2471C1101X',
 '2471C1106X',
 '2471C3401X',
 '2471C3402X',
 '2471M1202X',
 '2471M2300X',
 '2471N0900X',
 '2471Q0001X',
 '2471R0002X',
 '2471S1302X',
 '2471V0105X',
 '2471V0106X',
 '247200000X',
 '2472B0301X',
 '2472D0500X',
 '2472E0500X',
 '2472R0900X',
 '2472V0600X',
 '247ZC0005X',
 '251300000X',
 '251B00000X',
 '251C00000X',
 '251E00000X',
 '251F00000X',
 '251G00000X',
 '251J00000X',
 '251K00000X',
 '251S00000X',
 '251T00000X',
 '251V00000X',
 '251X00000X',
 '252Y00000X',
 '253J00000X',
 '253Z00000X',
 '261Q00000X',
 '261QA0005X',
 '261QA0006X',
 '261QA0600X',
 '261QA0900X',
 '261QA1903X',
 '261QA3000X',
 '261QB0400X',
 '261QC0050X',
 '261QC1500X',
 '261QC1800X',
 '261QD0000X',
 '261QD1600X',
 '261QE0002X',
 '261QE0700X',
 '261QE0800X',
 '261QF0050X',
 '261QF0400X',
 '261QG0250X',
 '261QH0100X',
 '261QH0700X',
 '261QI0500X',
 '261QM0801X',
 '261QM0850X',
 '261QM0855X',
 '261QM1100X',
 '261QM1101X',
 '261QM1102X',
 '261QM1103X',
 '261QM1200X',
 '261QM1300X',
 '261QM2500X',
 '261QM2800X',
 '261QM3000X',
 '261QP0904X',
 '261QP0905X',
 '261QP1100X',
 '261QP2000X',
 '261QP2300X',
 '261QP2400X',
 '261QP3300X',
 '261QR0200X',
 '261QR0206X',
 '261QR0207X',
 '261QR0208X',
 '261QR0400X',
 '261QR0401X',
 '261QR0404X',
 '261QR0405X',
 '261QR0800X',
 '261QR1100X',
 '261QR1300X',
 '261QS0112X',
 '261QS0132X',
 '261QS1000X',
 '261QS1200X',
 '261QU0200X',
 '261QV0200X',
 '261QX0100X',
 '261QX0200X',
 '261QX0203X',
 '273100000X',
 '273R00000X',
 '273Y00000X',
 '275N00000X',
 '276400000X',
 '281P00000X',
 '281PC2000X',
 '282E00000X',
 '282J00000X',
 '282N00000X',
 '282NC0060X',
 '282NC2000X',
 '282NR1301X',
 '282NW0100X',
 '283Q00000X',
 '283X00000X',
 '283XC2000X',
 '284300000X',
 '286500000X',
 '2865M2000X',
 '2865X1600X',
 '291900000X',
 '291U00000X',
 '292200000X',
 '293D00000X',
 '302F00000X',
 '302R00000X',
 '305R00000X',
 '305S00000X',
 '310400000X',
 '3104A0625X',
 '3104A0630X',
 '310500000X',
 '311500000X',
 '311Z00000X',
 '311ZA0620X',
 '313M00000X',
 '314000000X',
 '3140N1450X',
 '315D00000X',
 '315P00000X',
 '320600000X',
 '320700000X',
 '320800000X',
 '320900000X',
 '322D00000X',
 '323P00000X',
 '324500000X',
 '3245S0500X',
 '331L00000X',
 '332000000X',
 '332100000X',
 '332800000X',
 '332900000X',
 '332B00000X',
 '332BC3200X',
 '332BD1200X',
 '332BN1400X',
 '332BP3500X',
 '332BX2000X',
 '332H00000X',
 '332S00000X',
 '332U00000X',
 '333300000X',
 '333600000X',
 '3336C0002X',
 '3336C0003X',
 '3336C0004X',
 '3336H0001X',
 '3336I0012X',
 '3336L0003X',
 '3336M0002X',
 '3336M0003X',
 '3336N0007X',
 '3336S0011X',
 '335E00000X',
 '335G00000X',
 '335U00000X',
 '335V00000X',
 '341600000X',
 '3416A0800X',
 '3416L0300X',
 '3416S0300X',
 '3418M1110X',
 '3418M1130X',
 '342000000X',
 '343800000X',
 '343900000X',
 '344600000X',
 '347B00000X',
 '347C00000X',
 '347D00000X',
 '347E00000X',
 '363A00000X',
 '372500000X',
 '372600000X',
 '373H00000X',
 '374700000X',
 '3747A0650X',
 '3747P1801X',
 '374J00000X',
 '374K00000X',
 '374T00000X',
 '374U00000X',
 '376G00000X',
 '376J00000X',
 '376K00000X',
 '385H00000X',
 '385HR2050X',
 '385HR2055X',
 '385HR2060X',
 '385HR2065X',
 '405300000X'}

In [36]:
len(list(unique_taxonomy_codes))

489

In [37]:
df_nucc_lookup = pd.read_csv('./nucc_taxonomy_251.csv')

In [38]:
df_nucc_lookup
pd.set_option('display.max_rows', None)
df_nucc_lookup.head(30)

,Code,Grouping,Classification,Specialization,Definition,Notes,Display Name,Section
0,193200000X,Group,Multi-Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Multi-Specialty Group,Individual
1,193400000X,Group,Single Specialty,NaN,A business group of one or more individual pra...,[7/1/2003: new],Single Specialty Group,Individual
2,207K00000X,Allopathic & Osteopathic Physicians,Allergy & Immunology,NaN,An allergist-immunologist is trained in evalua...,"Source: American Board of Medical Specialties,...",Allergy & Immunology Physician,Individual
3,207KA0200X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Allergy,"A physician who specializes in the diagnosis, ...",Source: National Uniform Claim Committee,Allergy Physician,Individual
4,207KI0005X,Allopathic & Osteopathic Physicians,Allergy & Immunology,Clinical & Laboratory Immunology,An allergy and immunology physician who specia...,"Source: National Uniform Claim Committee, 2022...",Clinical & Laboratory Immunology (Allergy & Im...,Individual
5,207L00000X,Allopathic & Osteopathic Physicians,Anesthesiology,NaN,An anesthesiologist is trained to provide pain...,"Source: American Board of Medical Specialties,...",Anesthesiology Physician,Individual
6,207LA0401X,Allopathic & Osteopathic Physicians,Anesthesiology,Addiction Medicine,An anesthesiologist who specializes in the dia...,"Source: National Uniform Claim Committee, 2009...",Addiction Medicine (Anesthesiology) Physician,Individual
7,207LC0200X,Allopathic & Osteopathic Physicians,Anesthesiology,Critical Care Medicine,"An anesthesiologist, who specializes in critic...","Source: American Board of Medical Specialties,...",Critical Care Medicine (Anesthesiology) Physician,Individual
8,207LH0002X,Allopathic & Osteopathic Physicians,Anesthesiology,Hospice and Palliative Medicine,An anesthesiologist with special knowledge and...,Source: American Academy of Hospice and Pallia...,Hospice and Palliative Medicine (Anesthesiolog...,Individual
9,207LP2900X,Allopathic & Osteopathic Physicians,Anesthesiology,Pain Medicine,An anesthesiologist who provides a high level ...,"Source: American Board of Medical Specialties,...",Pain Medicine (Anesthesiology) Physician,Individual
10,207LP3000X,Allopathic & Osteopathic Physicians,Anesthesiology,Pediatric Anesthesiology,An anesthesiologist who has had additional ski...,"Source: American Academy of Pediatrics, www.aa...",Pediatric Anesthesiology Physician,Individual
11,207LP4000X,Allopathic & Osteopathic Physicians,Anesthesiology,Physician Nutrition Specialist,A physician who specializes in the diagnosis a...,Source: National Board of Physician Nutrition ...,Physician Nutrition Specialist (Anesthesiology),Individual
12,208U00000X,Allopathic & Osteopathic Physicians,Clinical Pharmacology,NaN,Clinical pharmacology encompasses the spectrum...,Source: American Society for Clinical Pharmaco...,Clinical Pharmacology Physician,Individual
13,208C00000X,Allopathic & Osteopathic Physicians,Colon & Rectal Surgery,NaN,A colon and rectal surgeon is trained to diagn...,"Source: American Board of Medical Specialties,...",Colon & Rectal Surgery Physician,Individual
14,207N00000X,Allopathic & Osteopathic Physicians,Dermatology,NaN,A dermatologist is trained to diagnose and tre...,"Source: American Board of Medical Specialties,...",Dermatology Physician,Individual
15,207NI0002X,Allopathic & Osteopathic Physicians,Dermatology,Clinical & Laboratory Dermatological Immunology,A dermatologist who utilizes various specializ...,"Source: American Board of Medical Specialties,...",Clinical & Laboratory Dermatological Immunolog...,Individual
16,207ND0900X,Allopathic & Osteopathic Physicians,Dermatology,Dermatopathology,A dermatopathologist has the expertise to diag...,"Source: American Board of Medical Specialties,...",Dermatopathology Physician,Individual
17,207ND0101X,Allopathic & Osteopathic Physicians,Dermatology,MOHS-Micrographic Surgery,The highly-trained surgeons that perform Mohs ...,"Source: American College of Mohs Surgery, 2007...",MOHS-Micrographic Surgery Physician,Individual
18,207NP0225X,Allopathic & Osteopathic Physicians,Dermatology,Pediatric Dermatology,"A pediatric dermatologist has, through additio...","Source: American Board of Medical Specialties,...",Pediatric Dermatology Physician,Individual
19,207NS0135X,Allopathic & Osteopathic Physicians,Dermatology,Procedural Dermatology,"Procedural Dermatology, a subspecialty of Derm...","Source: American Board of Dermatology, 2007, w...",Procedural Dermatology Physician,Individual
20,204R00000X,Allopathic & Osteopathic Physicians,Electrodiagnostic Medicine,NaN,Electrodiagnostic medicine is the medical subs...,Source: American Association of Neuromuscular ...,Electrodiagnostic Medicine Physician,Individual
21,207P00000X,Allopathic & Osteopathic Physicians,Emergency Medicine,NaN,An emergency physician focuses on the immediat...,"Source: American Board of Medical Specialties,...",Emergency Medicine Physician,Individual
22,207PE0004X,Allopathic & Osteopathic Physicians,Emergency Medicine,Emergency Medical Services,An emergency medicine physician who specialize...,"Source: National Uniform Claim Committee, 2009...",Emergency Medical Services (Emergency Medicine...,Individual
23,207PH0002X,Allopathic & Osteopathic Physicians,Emergency Medicine,Hospice and Palliative Medicine,An emergency medicine physician with special k...,Source: American Academy of Hospice and Pallia...,Hospice and Palliative Medicine (Emergency Med...,Individual
24,207PT0002X,Allopathic & Osteopathic Physicians,Emergency Medicine,Medical Toxicology,Medical toxicologists are physicians who speci...,"Source: American Board of Medical Specialties,...",Medical Toxicology (Emergency Medicine) Physician,Individual
25,207PP0204X,Allopathic & Osteopathic Physicians,Emergency Medicine,Pediatric Emergency Medicine,Pediatric Emergency Medicine is a clinical sub...,"Source: American Board of Medical Specialties,...",Pediatric Emergency Medicine (Emergency Medici...,Individual
26,207PS0010X,Allopathic & Osteopathic Physicians,Emergency Medicine,Sports Medicine,An emergency physician with special knowledge ...,"Source: American Board of Medical Specialties,...",Sports Medicine (Emergency Medicine) Physician,Individual
27,207PE0005X,Allopathic & Osteopathic Physicians,Emergency Medicine,Undersea and Hyperbaric Medicine,A specialist who treats decompression illness ...,Source: American Board of Emergency Medicine [...,Undersea and Hyperbaric Medicine (Emergency Me...,Individual
28,207Q00000X,Allopathic & Osteopathic Physicians,Family Medicine,NaN,Family Medicine is the medical specialty which...,Source: American Board of Family Medicine [1/...,Family Medicine Physician,Individual
29,207QA0401X,Allopathic & Osteopathic Physicians,Family Medicine,Addiction Medicine,A family medicine physician who specializes in...,"Source: National Uniform Claim Committee, 2009...",Addiction Medicine (Family Medicine) Physician,Individual

In [39]:
import json
with open('./taxonomycodes.json', 'r', encoding='utf-8-sig') as f:
    winnowcodes = json.load(f)

In [53]:
# Diagnostic: check file content
with open('./taxonomycodes.json', 'r', encoding='utf-8') as f:
    content = f.read()
    print(f"File length: {len(content)} characters")
    print(f"First 100 chars: {content[:100]}")
    print(f"Last 100 chars: {content[-100:]}")

File length: 62020 characters
First 100 chars: ﻿{
  "2086S0129X": {
    "taxonomy_code": "2086S0129X",
    "role": "Physician",
    "specialty": "S
Last 100 chars: : "Physical Medicine & Rehabilitation",
    "sub_specialty": "Hospice and Palliative Medicine"
  }
}

In [14]:
import json

# Create the output structure
output = {}

for code in unique_taxonomy_codes:
    output[code] = {
        "taxonomy_code": code,
        "role": "",
        "specialty": "",
        "sub_specialty": ""
    }

# Convert to JSON string with proper formatting
json_output = json.dumps(output, indent=2)
print(json_output)

{
  "226000000X": {
    "taxonomy_code": "226000000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246QM0706X": {
    "taxonomy_code": "246QM0706X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1744G0900X": {
    "taxonomy_code": "1744G0900X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "132700000X": {
    "taxonomy_code": "132700000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1223P0300X": {
    "taxonomy_code": "1223P0300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246QC1000X": {
    "taxonomy_code": "246QC1000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "193200000X": {
    "taxonomy_code": "193200000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "310500000X": {
    "taxonomy_code": "310500000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WI0500X": {
    "taxonomy_code": "163WI0500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "225B00000X": {
    "taxonomy_code": "225B00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QC1800X": {
    "taxonomy_code": "261QC1800X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471C1106X": {
    "taxonomy_code": "2471C1106X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471M2300X": {
    "taxonomy_code": "2471M2300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QM1101X": {
    "taxonomy_code": "261QM1101X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "343900000X": {
    "taxonomy_code": "343900000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "174V00000X": {
    "taxonomy_code": "174V00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QP2000X": {
    "taxonomy_code": "261QP2000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332BX2000X": {
    "taxonomy_code": "332BX2000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "343800000X": {
    "taxonomy_code": "343800000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "101YP2500X": {
    "taxonomy_code": "101YP2500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "311ZA0620X": {
    "taxonomy_code": "311ZA0620X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "251G00000X": {
    "taxonomy_code": "251G00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246ZB0600X": {
    "taxonomy_code": "246ZB0600X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WR0006X": {
    "taxonomy_code": "163WR0006X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332B00000X": {
    "taxonomy_code": "332B00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "284300000X": {
    "taxonomy_code": "284300000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "174MM1900X": {
    "taxonomy_code": "174MM1900X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332BC3200X": {
    "taxonomy_code": "332BC3200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3416L0300X": {
    "taxonomy_code": "3416L0300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QR0208X": {
    "taxonomy_code": "261QR0208X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WP0000X": {
    "taxonomy_code": "163WP0000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1223P0106X": {
    "taxonomy_code": "1223P0106X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "146D00000X": {
    "taxonomy_code": "146D00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WH0200X": {
    "taxonomy_code": "163WH0200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471C3402X": {
    "taxonomy_code": "2471C3402X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "281PC2000X": {
    "taxonomy_code": "281PC2000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3104A0630X": {
    "taxonomy_code": "3104A0630X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1835P1300X": {
    "taxonomy_code": "1835P1300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "156FX1202X": {
    "taxonomy_code": "156FX1202X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WN0800X": {
    "taxonomy_code": "163WN0800X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QP1100X": {
    "taxonomy_code": "261QP1100X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246YC3301X": {
    "taxonomy_code": "246YC3301X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QR1300X": {
    "taxonomy_code": "261QR1300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2279P3800X": {
    "taxonomy_code": "2279P3800X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WR1000X": {
    "taxonomy_code": "163WR1000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2278P3800X": {
    "taxonomy_code": "2278P3800X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WL0100X": {
    "taxonomy_code": "163WL0100X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "342000000X": {
    "taxonomy_code": "342000000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246RM2200X": {
    "taxonomy_code": "246RM2200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2279G0305X": {
    "taxonomy_code": "2279G0305X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3336S0011X": {
    "taxonomy_code": "3336S0011X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2278E1000X": {
    "taxonomy_code": "2278E1000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "283X00000X": {
    "taxonomy_code": "283X00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "251C00000X": {
    "taxonomy_code": "251C00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1835N0905X": {
    "taxonomy_code": "1835N0905X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "282J00000X": {
    "taxonomy_code": "282J00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WX0106X": {
    "taxonomy_code": "163WX0106X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "344600000X": {
    "taxonomy_code": "344600000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2279P1004X": {
    "taxonomy_code": "2279P1004X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WF0300X": {
    "taxonomy_code": "163WF0300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "171M00000X": {
    "taxonomy_code": "171M00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261Q00000X": {
    "taxonomy_code": "261Q00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246Z00000X": {
    "taxonomy_code": "246Z00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "174200000X": {
    "taxonomy_code": "174200000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "251S00000X": {
    "taxonomy_code": "251S00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3245S0500X": {
    "taxonomy_code": "3245S0500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "176P00000X": {
    "taxonomy_code": "176P00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2278P1005X": {
    "taxonomy_code": "2278P1005X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "335G00000X": {
    "taxonomy_code": "335G00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "174M00000X": {
    "taxonomy_code": "174M00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2278G1100X": {
    "taxonomy_code": "2278G1100X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QM1103X": {
    "taxonomy_code": "261QM1103X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471V0105X": {
    "taxonomy_code": "2471V0105X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "305S00000X": {
    "taxonomy_code": "305S00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QA0600X": {
    "taxonomy_code": "261QA0600X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "156F00000X": {
    "taxonomy_code": "156F00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471S1302X": {
    "taxonomy_code": "2471S1302X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471R0002X": {
    "taxonomy_code": "2471R0002X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "125J00000X": {
    "taxonomy_code": "125J00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "335E00000X": {
    "taxonomy_code": "335E00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246ZI1000X": {
    "taxonomy_code": "246ZI1000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3418M1130X": {
    "taxonomy_code": "3418M1130X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "171400000X": {
    "taxonomy_code": "171400000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "225400000X": {
    "taxonomy_code": "225400000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "282NR1301X": {
    "taxonomy_code": "282NR1301X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "311500000X": {
    "taxonomy_code": "311500000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1223X0008X": {
    "taxonomy_code": "1223X0008X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "183500000X": {
    "taxonomy_code": "183500000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "207RH0005X": {
    "taxonomy_code": "207RH0005X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "347B00000X": {
    "taxonomy_code": "347B00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "125Q00000X": {
    "taxonomy_code": "125Q00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QD1600X": {
    "taxonomy_code": "261QD1600X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WX1500X": {
    "taxonomy_code": "163WX1500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QM1200X": {
    "taxonomy_code": "261QM1200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QR0401X": {
    "taxonomy_code": "261QR0401X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "225A00000X": {
    "taxonomy_code": "225A00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246QL0901X": {
    "taxonomy_code": "246QL0901X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "177F00000X": {
    "taxonomy_code": "177F00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "331L00000X": {
    "taxonomy_code": "331L00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WW0000X": {
    "taxonomy_code": "163WW0000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "225CA2400X": {
    "taxonomy_code": "225CA2400X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "373H00000X": {
    "taxonomy_code": "373H00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "101YP1600X": {
    "taxonomy_code": "101YP1600X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246Q00000X": {
    "taxonomy_code": "246Q00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471M1202X": {
    "taxonomy_code": "2471M1202X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QS1200X": {
    "taxonomy_code": "261QS1200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "225CA2500X": {
    "taxonomy_code": "225CA2500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WA2000X": {
    "taxonomy_code": "163WA2000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "224ZE0001X": {
    "taxonomy_code": "224ZE0001X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332100000X": {
    "taxonomy_code": "332100000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QB0400X": {
    "taxonomy_code": "261QB0400X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2279S1500X": {
    "taxonomy_code": "2279S1500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "276400000X": {
    "taxonomy_code": "276400000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246ZX2200X": {
    "taxonomy_code": "246ZX2200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1041S0200X": {
    "taxonomy_code": "1041S0200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2278E0002X": {
    "taxonomy_code": "2278E0002X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "251E00000X": {
    "taxonomy_code": "251E00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WN0003X": {
    "taxonomy_code": "163WN0003X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QA3000X": {
    "taxonomy_code": "261QA3000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "103K00000X": {
    "taxonomy_code": "103K00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246RP1900X": {
    "taxonomy_code": "246RP1900X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3336C0003X": {
    "taxonomy_code": "3336C0003X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2471B0102X": {
    "taxonomy_code": "2471B0102X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1835N1003X": {
    "taxonomy_code": "1835N1003X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3418M1110X": {
    "taxonomy_code": "3418M1110X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "385H00000X": {
    "taxonomy_code": "385H00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "126900000X": {
    "taxonomy_code": "126900000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WM0705X": {
    "taxonomy_code": "163WM0705X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "314000000X": {
    "taxonomy_code": "314000000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332U00000X": {
    "taxonomy_code": "332U00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1835P0200X": {
    "taxonomy_code": "1835P0200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QS1000X": {
    "taxonomy_code": "261QS1000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1744R1102X": {
    "taxonomy_code": "1744R1102X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "2472B0301X": {
    "taxonomy_code": "2472B0301X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QU0200X": {
    "taxonomy_code": "261QU0200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1223D0004X": {
    "taxonomy_code": "1223D0004X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "202K00000X": {
    "taxonomy_code": "202K00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332900000X": {
    "taxonomy_code": "332900000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "202C00000X": {
    "taxonomy_code": "202C00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "209800000X": {
    "taxonomy_code": "209800000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332H00000X": {
    "taxonomy_code": "332H00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "251K00000X": {
    "taxonomy_code": "251K00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "207VC0300X": {
    "taxonomy_code": "207VC0300X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "164W00000X": {
    "taxonomy_code": "164W00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "163WX0002X": {
    "taxonomy_code": "163WX0002X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "101Y00000X": {
    "taxonomy_code": "101Y00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "324500000X": {
    "taxonomy_code": "324500000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1223D0001X": {
    "taxonomy_code": "1223D0001X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1835X0200X": {
    "taxonomy_code": "1835X0200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "320900000X": {
    "taxonomy_code": "320900000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1744P3200X": {
    "taxonomy_code": "1744P3200X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "167G00000X": {
    "taxonomy_code": "167G00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "146M00000X": {
    "taxonomy_code": "146M00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "305R00000X": {
    "taxonomy_code": "305R00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "332000000X": {
    "taxonomy_code": "332000000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "261QM0850X": {
    "taxonomy_code": "261QM0850X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "171R00000X": {
    "taxonomy_code": "171R00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "247100000X": {
    "taxonomy_code": "247100000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "273100000X": {
    "taxonomy_code": "273100000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "225CX0006X": {
    "taxonomy_code": "225CX0006X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "322D00000X": {
    "taxonomy_code": "322D00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246XS1301X": {
    "taxonomy_code": "246XS1301X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246ZE0500X": {
    "taxonomy_code": "246ZE0500X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246QB0000X": {
    "taxonomy_code": "246QB0000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "3747P1801X": {
    "taxonomy_code": "3747P1801X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "1835S0206X": {
    "taxonomy_code": "1835S0206X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "171W00000X": {
    "taxonomy_code": "171W00000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },
  "246QI0000X": {
    "taxonomy_code": "246QI0000X",
    "role": "",
    "specialty": "",
    "sub_specialty": ""
  },

In [23]:
import json
import re
from collections import Counter

file_path = '/Users/tomcraig/dev/ETL/WinnowPackages/Aya.Winnow.Domain.Model/Taxonomies/taxonomycodes.json'

# Read the raw text using utf-8-sig to handle BOM
with open(file_path, 'r', encoding='utf-8-sig') as f:
    content = f.read()

# Load as JSON into a dict
taxonomy_data = json.loads(content)

# List keys from the dict
keys = list(taxonomy_data.keys())
print(f"Total keys: {len(keys)}")
print(keys)

Total keys: 863
['2086S0129X', '207RN0300X', '207NI0002X', '152WL0500X', '207RA0401X', '204D00000X', '103TB0200X', '207ZP0104X', '364SX0204X', '152WX0102X', '2086S0122X', '364SR0400X', '207QA0000X', '207ND0101X', '207PH0002X', '364SF0001X', '364SP1700X', '2083T0002X', '207SG0201X', '207R00000X', '133VN1401X', '207UN0903X', '2080T0002X', '2084B0002X', '111NR0400X', '2251H1300X', '207RA0002X', '2084F0202X', '208M00000X', '2080P0008X', '364SL0600X', '367H00000X', '207ZI0100X', '207QB0002X', '2251X0800X', '2082S0105X', '207RH0003X', '363A00000X', '207RG0100X', '2251P0200X', '2083A0300X', '103TF0200X', '207X00000X', '213ER0200X', '163WC3500X', '103TC0700X', '207RA0001X', '363LC1500X', '231H00000X', '207RI0008X', '225XL0004X', '363LA2100X', '2086H0002X', '207ZH0000X', '207RX0202X', '2251S0007X', '207Q00000X', '106S00000X', '364SX0106X', '207QA0401X', '208800000X', '213ES0000X', '207QA0505X', '225XP0019X', '103TC1900X', '106E00000X', '364SP0811X', '207RS0012X', '2080P0203X', '207RR0500X', '207RB0002X', '2086S0102X', '207YX0905X', '207VX0000X', '103TA0700X', '207P00000X', '103TR0400X', '208D00000X', '2084P0800X', '225XN1300X', '2085P0229X', '2081N0008X', '207RG0300X', '213EG0000X', '208200000X', '2084P0802X', '207YS0123X', '363LP1700X', '364SP0809X', '2083P0500X', '2084S0010X', '207VX0201X', '2084P0005X', '225XE0001X', '207RS0010X', '207YP0228X', '103TH0004X', '103TM1800X', '207XP3100X', '207VF0040X', '208600000X', '207VG0400X', '363LS0200X', '2080P0210X', '103T00000X', '103TP0016X', '2084N0402X', '207RC0200X', '213EP0504X', '225100000X', '208C00000X', '213EP1101X', '2080A0000X', '363LX0106X', '204C00000X', '231HA2500X', '2084P2900X', '2081P0004X', '2086S0120X', '364SN0800X', '207ZB0001X', '364SE1400X', '122300000X', '2080H0002X', '111N00000X', '2084A2900X', '207N00000X', '207SG0203X', '207XS0117X', '2081P0010X', '364SX0200X', '207SG0205X', '103TW0100X', '174400000X', '2080P0208X', '2083X0100X', '364SE0003X', '2251H1200X', '2084D0003X', '207XX0801X', '207ZC0500X', '207RM1200X', '103TC2200X', '207RA0201X', '207LP2900X', '2085N0904X', '207U00000X', '225XE1200X', '103TM1700X', '363LA2200X', '213ES0103X', '364SP0807X', '207RH0000X', '364SA2100X', '207RT0003X', '103TP0814X', '207LH0002X', '207UN0901X', '2080S0010X', '363LF0000X', '207NS0135X', '207SM0001X', '2085R0204X', '363AM0700X', '207L00000X', '207PT0002X', '103TA0400X', '111NN0400X', '133VN1301X', '207WX0120X', '364ST0500X', '207W00000X', '364SC2300X', '111NT0100X', '103TS0200X', '207KA0200X', '363LC0200X', '2085D0003X', '207QS1201X', '2080P0202X', '363LP2300X', '207ZM0300X', '364SA2200X', '2080P0006X', '364SP0200X', '111NN1001X', '207KI0005X', '208000000X', '364SC0200X', '207VH0002X', '2084S0012X', '2251C2600X', '2080P0205X', '207YX0602X', '208100000X', '207RI0001X', '2251G0304X', '225X00000X', '2084P0301X', '229N00000X', '207VB0002X', '2084B0040X', '213ES0131X', '364SN0000X', '103TP2701X', '207RC0000X', '225XR0403X', '363LN0005X', '2083S0010X', '133VN1501X', '208G00000X', '2251E1300X', '363LP0200X', '364SP0808X', '207WX0109X', '207VE0102X', '2081P0301X', '2083B0002X', '2084N0400X', '225XF0002X', '2086S0105X', '367500000X', '111NR0200X', '111NI0900X', '207ZD0900X', '207T00000X', '1223G0001X', '207PP0204X', '103TF0000X', '2080T0004X', '207RH0002X', '207K00000X', '133VN1101X', '207QG0300X', '364S00000X', '207YS0012X', '364SH1100X', '207RI0011X', '225XH1200X', '207YX0007X', '364SP0813X', '207XX0005X', '207QS0010X', '207ZF0201X', '2082S0099X', '225XP0200X', '2085R0001X', '2080B0002X', '2083P0011X', '207LA0401X', '204E00000X', '2084A0401X', '207LP3000X', '1041C0700X', '363LX0001X', '364SP0810X', '2083P0901X', '103TH0100X', '152WS0006X', '364SP0812X', '363LG0600X', '2080P0204X', '207NP0225X', '364SI0800X', '207VC0200X', '213E00000X', '2080P0214X', '222Z00000X', '364SG0600X', '364SH0200X', '1223S0112X', '207PE0004X', '364SC1501X', '207UN0902X', '103TE1100X', '103TP2700X', '2080S0012X', '224P00000X', '2080C0008X', '2084V0102X', '207XX0004X', '2251N0400X', '207ZP0213X', '207RC0001X', '2080P0206X', '152W00000X', '111NS0005X', '364SM0705X', '2081P2900X', '2080P0201X', '207Y00000X', '225XM0800X', '207WX0110X', '207YX0901X', '2084N0008X', '2085N0700X', '133VN1006X', '207WX0009X', '207ZP0007X', '231HA2400X', '207SG0202X', '207QH0002X', '207PS0010X', '2088P0231X', '152WV0400X', '2085U0001X', '207RA0000X', '207ZP0101X', '225XG0600X', '363LN0000X', '2080I0007X', '2084N0600X', '207RP1001X', '133VN1005X', '2084H0002X', '2083C0008X', '207RE0101X', '207WX0200X', '363L00000X', '2084E0001X', '207PE0005X', '207XS0106X', '133V00000X', '390200000X', '2080N0001X', '207ZP0102X', '111NX0100X', '207ZP0105X', '207VM0101X', '152WP0200X', '2251E1200X', '2084P0805X', '363LW0102X', '152WC0802X', '367A00000X', '2083A0100X', '2086X0206X', '2080P0216X', '2084P0015X', '207XS0114X', '2084P0804X', '207RI0200X', '235Z00000X', '2085R0202X', '207LC0200X', '207V00000X', '363AS0400X', '103TE1000X', '156FX1800X', '2088F0040X', '111NI0013X', '133VN1004X', '364SS0200X', '2085R0205X', '225XH1300X', '207ZC0006X', '207ZC0008X', '207WX0108X', '204F00000X', '363LP0808X', '363LP0222X', '364SW0102X', '2080P0207X', '207ND0900X', '207ZN0500X', '2081S0010X', '364SP2800X', '208VP0014X', '111NP0017X', '133VN1201X', '111NX0800X', '2086S0127X', '207WX0107X', '156FX1700X', '2081H0002X', '226000000X', '246QM0706X', '1744G0900X', '132700000X', '1223P0300X', '246QC1000X', '193200000X', '310500000X', '163WI0500X', '225B00000X', '261QC1800X', '2471C1106X', '2471M2300X', '261QM1101X', '343900000X', '174V00000X', '261QP2000X', '332BX2000X', '343800000X', '101YP2500X', '311ZA0620X', '251G00000X', '246ZB0600X', '163WR0006X', '332B00000X', '284300000X', '174MM1900X', '332BC3200X', '3416L0300X', '261QR0208X', '163WP0000X', '1223P0106X', '146D00000X', '163WH0200X', '2471C3402X', '281PC2000X', '3104A0630X', '1835P1300X', '156FX1202X', '163WN0800X', '261QP1100X', '246YC3301X', '261QR1300X', '2279P3800X', '163WR1000X', '2278P3800X', '163WL0100X', '342000000X', '246RM2200X', '2279G0305X', '3336S0011X', '2278E1000X', '283X00000X', '251C00000X', '1835N0905X', '282J00000X', '163WX0106X', '344600000X', '2279P1004X', '163WF0300X', '171M00000X', '261Q00000X', '246Z00000X', '174200000X', '251S00000X', '3245S0500X', '176P00000X', '2278P1005X', '335G00000X', '174M00000X', '2278G1100X', '261QM1103X', '2471V0105X', '305S00000X', '261QA0600X', '156F00000X', '2471S1302X', '2471R0002X', '125J00000X', '335E00000X', '246ZI1000X', '3418M1130X', '171400000X', '225400000X', '282NR1301X', '311500000X', '1223X0008X', '183500000X', '207RH0005X', '347B00000X', '125Q00000X', '261QD1600X', '163WX1500X', '261QM1200X', '261QR0401X', '225A00000X', '246QL0901X', '177F00000X', '331L00000X', '163WW0000X', '225CA2400X', '373H00000X', '101YP1600X', '246Q00000X', '2471M1202X', '261QS1200X', '225CA2500X', '163WA2000X', '224ZE0001X', '332100000X', '261QB0400X', '2279S1500X', '276400000X', '246ZX2200X', '1041S0200X', '2278E0002X', '251E00000X', '163WN0003X', '261QA3000X', '103K00000X', '246RP1900X', '3336C0003X', '2471B0102X', '1835N1003X', '3418M1110X', '385H00000X', '126900000X', '163WM0705X', '314000000X', '332U00000X', '1835P0200X', '261QS1000X', '1744R1102X', '2472B0301X', '261QU0200X', '1223D0004X', '202K00000X', '332900000X', '202C00000X', '209800000X', '332H00000X', '251K00000X', '207VC0300X', '164W00000X', '163WX0002X', '101Y00000X', '324500000X', '1223D0001X', '1835X0200X', '320900000X', '1744P3200X', '167G00000X', '146M00000X', '305R00000X', '332000000X', '261QM0850X', '171R00000X', '247100000X', '273100000X', '225CX0006X', '322D00000X', '246XS1301X', '246ZE0500X', '246QB0000X', '3747P1801X', '1835S0206X', '171W00000X', '246QI0000X', '163WH1000X', '1710I1003X', '1835P2201X', '224ZF0002X', '3104A0625X', '163WI0600X', '146L00000X', '2278P3900X', '163WD1100X', '3336M0002X', '237700000X', '1223P0221X', '385HR2065X', '251300000X', '3416S0300X', '1835P1200X', '247200000X', '2471V0106X', '3336L0003X', '376G00000X', '163WM0102X', '173000000X', '261QR0400X', '246ZA2600X', '246YR1600X', '163WW0101X', '136A00000X', '246RH0600X', '333300000X', '2472D0500X', '2472E0500X', '171100000X', '193400000X', '163WD0400X', '146N00000X', '207SC0300X', '261QR0200X', '261QA0005X', '221700000X', '163WS0121X', '225600000X', '106H00000X', '2278H0200X', '156FC0800X', '335U00000X', '2279C0205X', '261QA1903X', '163WR0400X', '242T00000X', '251V00000X', '246QH0000X', '163WX0601X', '3336M0003X', '163WP2201X', '261QS0132X', '2470A2800X', '282NW0100X', '171WH0202X', '225000000X', '2278C0205X', '156FX1201X', '374700000X', '385HR2055X', '163WC0400X', '261QP0905X', '253J00000X', '1835C0206X', '163WH0500X', '261QM0801X', '246XC2901X', '261QM1300X', '261QM1100X', '246QM0900X', '341600000X', '320600000X', '2279E1000X', '246QC2700X', '227900000X', '261QI0500X', '172V00000X', '171WV0202X', '156FX1101X', '2865M2000X', '261QM2500X', '246ZE0600X', '133N00000X', '163WC1500X', '224Y00000X', '405300000X', '376K00000X', '163WP0809X', '246W00000X', '164X00000X', '261QE0002X', '251J00000X', '246XC2903X', '261QF0400X', '202D00000X', '173F00000X', '183700000X', '224ZR0403X', '302F00000X', '1835C0207X', '3416A0800X', '332S00000X', '320800000X', '261QX0100X', '124Q00000X', '2279P1006X', '3747A0650X', '101YM0800X', '2278G0305X', '261QG0250X', '2355S0801X', '2279G1100X', '163WU0100X', '261QM0855X', '246QH0401X', '253Z00000X', '261QX0203X', '246QH0600X', '261QR0207X', '163WM1400X', '261QR1100X', '104100000X', '163WG0600X', '372500000X', '2865X1600X', '261QS0112X', '347D00000X', '2279P1005X', '261QM1102X', '291U00000X', '311Z00000X', '163WC2100X', '332800000X', '332BN1400X', '2085B0100X', '163WE0003X', '2279P3900X', '163WP0200X', '163WX0200X', '163WP0807X', '282N00000X', '163WG0000X', '246ZB0500X', '310400000X', '103G00000X', '282NC2000X', '3336I0012X', '163WN0300X', '163WP0808X', '2279P4000X', '374J00000X', '225800000X', '163WX0800X', '126800000X', '261QP0904X', '133NN1002X', '3336H0001X', '246ZC0007X', '176B00000X', '2355A2700X', '235500000X', '251T00000X', '2278P4000X', '175F00000X', '175M00000X', '102L00000X', '286500000X', '225C00000X', '261QF0050X', '251F00000X', '291900000X', '224L00000X', '347C00000X', '320700000X', '1835G0303X', '273Y00000X', '226300000X', '243U00000X', '385HR2060X', '261QR0404X', '246QL0900X', '246ZN0300X', '3336C0004X', '302R00000X', '252Y00000X', '374U00000X', '2085R0203X', '261QX0200X', '102X00000X', '163WC1400X', '101200000X', '163WN1003X', '172P00000X', '1223E0200X', '1835I0206X', '323P00000X', '376J00000X', '2278P1006X', '347E00000X', '3336C0002X', '273R00000X', '2085H0002X', '261QR0405X', '261QD0000X', '222Q00000X', '1835P0018X', '261QR0800X', '163WX0003X', '227800000X', '246X00000X', '163WP0218X', '2471C3401X', '261QM2800X', '101YS0200X', '208U00000X', '335V00000X', '208VP0000X', '207SG0207X', '261QC0050X', '261QC1500X', '163WC0200X', '261QV0200X', '333600000X', '156FX1100X', '211D00000X', '3336N0007X', '2279E0002X', '374T00000X', '163WX1100X', '163WS0200X', '315P00000X', '246YC3302X', '175T00000X', '171000000X', '163WC1600X', '2471C1101X', '125K00000X', '174H00000X', '1710I1002X', '204R00000X', '156FC0801X', '315D00000X', '225200000X', '261QH0700X', '237600000X', '261QH0100X', '1223X0400X', '1223X2210X', '2255A2300X', '224ZL0004X', '2279H0200X', '261QR0206X', '283Q00000X', '246R00000X', '172M00000X', '163WE0900X', '246ZG0701X', '163WG0100X', '282E00000X', '261QP2400X', '224900000X', '261QA0006X', '332BP3500X', '275N00000X', '332BD1200X', '246ZB0302X', '163WA0400X', '163WP1700X', '2278S1500X', '225500000X', '313M00000X', '2255R0406X', '281P00000X', '261QP2300X', '156FX1900X', '224Z00000X', '225700000X', '261QA0900X', '293D00000X', '174N00000X', '246ZS0410X', '251X00000X', '175L00000X', '170300000X', '2472R0900X', '1835C0205X', '2472V0600X', '172A00000X', '1835E0208X', '261QE0800X', '246ZG1000X', '2278P1004X', '170100000X', '2471Q0001X', '283XC2000X', '1744R1103X', '282NC0060X', '173C00000X', '122400000X', '163WN0002X', '251B00000X', '385HR2050X', '247000000X', '246Y00000X', '374K00000X', '246ZB0301X', '3140N1450X', '372600000X', '247ZC0005X', '163W00000X', '1223P0700X', '261QE0700X', '292200000X', '101YA0400X', '261QM3000X', '2471N0900X', '261QP3300X']

In [26]:
# Find taxonomy codes from the JSON that exist in df_nucc_lookup.code
json_keys_set = set(keys)
nucc_codes = set(df_nucc_lookup['Code'].astype(str))

present_in_lookup = df_nucc_lookup[df_nucc_lookup['Code'].astype(str).isin(json_keys_set)]
missing_in_lookup = sorted(json_keys_set - nucc_codes)

print(f"Codes found in df_nucc_lookup: {len(present_in_lookup)}")
print(present_in_lookup[['Code']])
print(f"\nCodes missing from df_nucc_lookup: {len(missing_in_lookup)}")
if missing_in_lookup:
    print(missing_in_lookup)
else:
    print("None")

Codes found in df_nucc_lookup: 863
           Code
0    193200000X
1    193400000X
2    207K00000X
3    207KA0200X
4    207KI0005X
..          ...
878  343800000X
879  344600000X
880  347D00000X
881  347E00000X
882  342000000X

[863 rows x 1 columns]

Codes missing from df_nucc_lookup: 0
None

In [41]:
import json
import pandas as pd

# Build updated JSON using codes present in both the taxonomy file and df_nucc_lookup
code_col = 'Code' if 'Code' in df_nucc_lookup.columns else 'code'
classification_col = 'Classification' if 'Classification' in df_nucc_lookup.columns else 'classification'
specialization_col = 'Specialization' if 'Specialization' in df_nucc_lookup.columns else 'specialization'

json_keys_set = set(unique_taxonomy_codes)
nucc_filtered = df_nucc_lookup[df_nucc_lookup[code_col].astype(str).isin(json_keys_set)]

# Helper to clean string values
clean = lambda val: "" if pd.isna(val) else str(val).strip()

output_json = {}
for _, row in nucc_filtered.iterrows():
    code_val = str(row[code_col]).strip()
    output_json[code_val] = {
        "taxonomy_code": code_val,
        "role": "",
        "specialty": clean(row[classification_col]),
        "sub_specialty": clean(row[specialization_col])
    }

print(json.dumps(output_json, indent=2))

{
  "193200000X": {
    "taxonomy_code": "193200000X",
    "role": "",
    "specialty": "Multi-Specialty",
    "sub_specialty": ""
  },
  "193400000X": {
    "taxonomy_code": "193400000X",
    "role": "",
    "specialty": "Single Specialty",
    "sub_specialty": ""
  },
  "208U00000X": {
    "taxonomy_code": "208U00000X",
    "role": "",
    "specialty": "Clinical Pharmacology",
    "sub_specialty": ""
  },
  "204R00000X": {
    "taxonomy_code": "204R00000X",
    "role": "",
    "specialty": "Electrodiagnostic Medicine",
    "sub_specialty": ""
  },
  "202C00000X": {
    "taxonomy_code": "202C00000X",
    "role": "",
    "specialty": "Independent Medical Examiner",
    "sub_specialty": ""
  },
  "202D00000X": {
    "taxonomy_code": "202D00000X",
    "role": "",
    "specialty": "Integrative Medicine",
    "sub_specialty": ""
  },
  "207RH0005X": {
    "taxonomy_code": "207RH0005X",
    "role": "",
    "specialty": "Internal Medicine",
    "sub_specialty": "Hypertension Specialist"
  },
  "209800000X": {
    "taxonomy_code": "209800000X",
    "role": "",
    "specialty": "Legal Medicine",
    "sub_specialty": ""
  },
  "207SC0300X": {
    "taxonomy_code": "207SC0300X",
    "role": "",
    "specialty": "Medical Genetics",
    "sub_specialty": "Clinical Cytogenetics"
  },
  "207SG0207X": {
    "taxonomy_code": "207SG0207X",
    "role": "",
    "specialty": "Medical Genetics",
    "sub_specialty": "Medical Biochemical Genetics"
  },
  "207VC0300X": {
    "taxonomy_code": "207VC0300X",
    "role": "",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Complex Family Planning"
  },
  "208VP0000X": {
    "taxonomy_code": "208VP0000X",
    "role": "",
    "specialty": "Pain Medicine",
    "sub_specialty": "Pain Medicine"
  },
  "202K00000X": {
    "taxonomy_code": "202K00000X",
    "role": "",
    "specialty": "Phlebology",
    "sub_specialty": ""
  },
  "2085B0100X": {
    "taxonomy_code": "2085B0100X",
    "role": "",
    "specialty": "Radiology",
    "sub_specialty": "Body Imaging"
  },
  "2085H0002X": {
    "taxonomy_code": "2085H0002X",
    "role": "",
    "specialty": "Radiology",
    "sub_specialty": "Hospice and Palliative Medicine"
  },
  "2085R0203X": {
    "taxonomy_code": "2085R0203X",
    "role": "",
    "specialty": "Radiology",
    "sub_specialty": "Therapeutic Radiology"
  },
  "103K00000X": {
    "taxonomy_code": "103K00000X",
    "role": "",
    "specialty": "Behavior Analyst",
    "sub_specialty": ""
  },
  "103G00000X": {
    "taxonomy_code": "103G00000X",
    "role": "",
    "specialty": "Clinical Neuropsychologist",
    "sub_specialty": ""
  },
  "101Y00000X": {
    "taxonomy_code": "101Y00000X",
    "role": "",
    "specialty": "Counselor",
    "sub_specialty": ""
  },
  "101YA0400X": {
    "taxonomy_code": "101YA0400X",
    "role": "",
    "specialty": "Counselor",
    "sub_specialty": "Addiction (Substance Use Disorder)"
  },
  "101YM0800X": {
    "taxonomy_code": "101YM0800X",
    "role": "",
    "specialty": "Counselor",
    "sub_specialty": "Mental Health"
  },
  "101YP1600X": {
    "taxonomy_code": "101YP1600X",
    "role": "",
    "specialty": "Counselor",
    "sub_specialty": "Pastoral"
  },
  "101YP2500X": {
    "taxonomy_code": "101YP2500X",
    "role": "",
    "specialty": "Counselor",
    "sub_specialty": "Professional"
  },
  "101YS0200X": {
    "taxonomy_code": "101YS0200X",
    "role": "",
    "specialty": "Counselor",
    "sub_specialty": "School"
  },
  "101200000X": {
    "taxonomy_code": "101200000X",
    "role": "",
    "specialty": "Drama Therapist",
    "sub_specialty": ""
  },
  "106H00000X": {
    "taxonomy_code": "106H00000X",
    "role": "",
    "specialty": "Marriage & Family Therapist",
    "sub_specialty": ""
  },
  "102X00000X": {
    "taxonomy_code": "102X00000X",
    "role": "",
    "specialty": "Poetry Therapist",
    "sub_specialty": ""
  },
  "102L00000X": {
    "taxonomy_code": "102L00000X",
    "role": "",
    "specialty": "Psychoanalyst",
    "sub_specialty": ""
  },
  "104100000X": {
    "taxonomy_code": "104100000X",
    "role": "",
    "specialty": "Social Worker",
    "sub_specialty": ""
  },
  "1041S0200X": {
    "taxonomy_code": "1041S0200X",
    "role": "",
    "specialty": "Social Worker",
    "sub_specialty": "School"
  },
  "125K00000X": {
    "taxonomy_code": "125K00000X",
    "role": "",
    "specialty": "Advanced Practice Dental Therapist",
    "sub_specialty": ""
  },
  "126800000X": {
    "taxonomy_code": "126800000X",
    "role": "",
    "specialty": "Dental Assistant",
    "sub_specialty": ""
  },
  "124Q00000X": {
    "taxonomy_code": "124Q00000X",
    "role": "",
    "specialty": "Dental Hygienist",
    "sub_specialty": ""
  },
  "126900000X": {
    "taxonomy_code": "126900000X",
    "role": "",
    "specialty": "Dental Laboratory Technician",
    "sub_specialty": ""
  },
  "125J00000X": {
    "taxonomy_code": "125J00000X",
    "role": "",
    "specialty": "Dental Therapist",
    "sub_specialty": ""
  },
  "1223D0004X": {
    "taxonomy_code": "1223D0004X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Dental Anesthesiology"
  },
  "1223D0001X": {
    "taxonomy_code": "1223D0001X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Dental Public Health"
  },
  "1223E0200X": {
    "taxonomy_code": "1223E0200X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Endodontics"
  },
  "1223P0106X": {
    "taxonomy_code": "1223P0106X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Oral and Maxillofacial Pathology"
  },
  "1223X0008X": {
    "taxonomy_code": "1223X0008X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Oral and Maxillofacial Radiology"
  },
  "125Q00000X": {
    "taxonomy_code": "125Q00000X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Oral Medicine"
  },
  "1223X2210X": {
    "taxonomy_code": "1223X2210X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Orofacial Pain"
  },
  "1223X0400X": {
    "taxonomy_code": "1223X0400X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Orthodontics and Dentofacial Orthopedics"
  },
  "1223P0221X": {
    "taxonomy_code": "1223P0221X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Pediatric Dentistry"
  },
  "1223P0300X": {
    "taxonomy_code": "1223P0300X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Periodontics"
  },
  "1223P0700X": {
    "taxonomy_code": "1223P0700X",
    "role": "",
    "specialty": "Dentist",
    "sub_specialty": "Prosthodontics"
  },
  "122400000X": {
    "taxonomy_code": "122400000X",
    "role": "",
    "specialty": "Denturist",
    "sub_specialty": ""
  },
  "132700000X": {
    "taxonomy_code": "132700000X",
    "role": "",
    "specialty": "Dietary Manager",
    "sub_specialty": ""
  },
  "136A00000X": {
    "taxonomy_code": "136A00000X",
    "role": "",
    "specialty": "Dietetic Technician, Registered",
    "sub_specialty": ""
  },
  "133N00000X": {
    "taxonomy_code": "133N00000X",
    "role": "",
    "specialty": "Nutritionist",
    "sub_specialty": ""
  },
  "133NN1002X": {
    "taxonomy_code": "133NN1002X",
    "role": "",
    "specialty": "Nutritionist",
    "sub_specialty": "Nutrition, Education"
  },
  "146N00000X": {
    "taxonomy_code": "146N00000X",
    "role": "",
    "specialty": "Emergency Medical Technician, Basic",
    "sub_specialty": ""
  },
  "146M00000X": {
    "taxonomy_code": "146M00000X",
    "role": "",
    "specialty": "Emergency Medical Technician, Intermediate",
    "sub_specialty": ""
  },
  "146L00000X": {
    "taxonomy_code": "146L00000X",
    "role": "",
    "specialty": "Emergency Medical Technician, Paramedic",
    "sub_specialty": ""
  },
  "146D00000X": {
    "taxonomy_code": "146D00000X",
    "role": "",
    "specialty": "Personal Emergency Response Attendant",
    "sub_specialty": ""
  },
  "156F00000X": {
    "taxonomy_code": "156F00000X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": ""
  },
  "156FC0800X": {
    "taxonomy_code": "156FC0800X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Contact Lens"
  },
  "156FC0801X": {
    "taxonomy_code": "156FC0801X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Contact Lens Fitter"
  },
  "156FX1100X": {
    "taxonomy_code": "156FX1100X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Ophthalmic"
  },
  "156FX1101X": {
    "taxonomy_code": "156FX1101X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Ophthalmic Assistant"
  },
  "156FX1201X": {
    "taxonomy_code": "156FX1201X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Optometric Assistant"
  },
  "156FX1202X": {
    "taxonomy_code": "156FX1202X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Optometric Technician"
  },
  "156FX1900X": {
    "taxonomy_code": "156FX1900X",
    "role": "",
    "specialty": "Technician/Technologist",
    "sub_specialty": "Orthoptist"
  },
  "164W00000X": {
    "taxonomy_code": "164W00000X",
    "role": "",
    "specialty": "Licensed Practical Nurse",
    "sub_specialty": ""
  },
  "167G00000X": {
    "taxonomy_code": "167G00000X",
    "role": "",
    "specialty": "Licensed Psychiatric Technician",
    "sub_specialty": ""
  },
  "164X00000X": {
    "taxonomy_code": "164X00000X",
    "role": "",
    "specialty": "Licensed Vocational Nurse",
    "sub_specialty": ""
  },
  "163W00000X": {
    "taxonomy_code": "163W00000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": ""
  },
  "163WA0400X": {
    "taxonomy_code": "163WA0400X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Addiction (Substance Use Disorder)"
  },
  "163WA2000X": {
    "taxonomy_code": "163WA2000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Administrator"
  },
  "163WP2201X": {
    "taxonomy_code": "163WP2201X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Ambulatory Care"
  },
  "163WC0400X": {
    "taxonomy_code": "163WC0400X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Case Management"
  },
  "163WC1400X": {
    "taxonomy_code": "163WC1400X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "College Health"
  },
  "163WC1500X": {
    "taxonomy_code": "163WC1500X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Community Health"
  },
  "163WC2100X": {
    "taxonomy_code": "163WC2100X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Continence Care"
  },
  "163WC1600X": {
    "taxonomy_code": "163WC1600X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Continuing Education/Staff Development"
  },
  "163WC0200X": {
    "taxonomy_code": "163WC0200X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Critical Care Medicine"
  },
  "163WD0400X": {
    "taxonomy_code": "163WD0400X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Diabetes Educator"
  },
  "163WD1100X": {
    "taxonomy_code": "163WD1100X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Dialysis, Peritoneal"
  },
  "163WE0003X": {
    "taxonomy_code": "163WE0003X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Emergency"
  },
  "163WE0900X": {
    "taxonomy_code": "163WE0900X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Enterostomal Therapy"
  },
  "163WF0300X": {
    "taxonomy_code": "163WF0300X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Flight"
  },
  "163WG0100X": {
    "taxonomy_code": "163WG0100X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Gastroenterology"
  },
  "163WG0000X": {
    "taxonomy_code": "163WG0000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "General Practice"
  },
  "163WG0600X": {
    "taxonomy_code": "163WG0600X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Gerontology"
  },
  "163WH0500X": {
    "taxonomy_code": "163WH0500X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Hemodialysis"
  },
  "163WH0200X": {
    "taxonomy_code": "163WH0200X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Home Health"
  },
  "163WH1000X": {
    "taxonomy_code": "163WH1000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Hospice"
  },
  "163WI0600X": {
    "taxonomy_code": "163WI0600X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Infection Control"
  },
  "163WI0500X": {
    "taxonomy_code": "163WI0500X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Infusion Therapy"
  },
  "163WL0100X": {
    "taxonomy_code": "163WL0100X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Lactation Consultant"
  },
  "163WM0102X": {
    "taxonomy_code": "163WM0102X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Maternal Newborn"
  },
  "163WM0705X": {
    "taxonomy_code": "163WM0705X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Medical-Surgical"
  },
  "163WN0002X": {
    "taxonomy_code": "163WN0002X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Neonatal Intensive Care"
  },
  "163WN0003X": {
    "taxonomy_code": "163WN0003X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Neonatal, Low-Risk"
  },
  "163WN0300X": {
    "taxonomy_code": "163WN0300X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Nephrology"
  },
  "163WN0800X": {
    "taxonomy_code": "163WN0800X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Neuroscience"
  },
  "163WM1400X": {
    "taxonomy_code": "163WM1400X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Nurse Massage Therapist (NMT)"
  },
  "163WN1003X": {
    "taxonomy_code": "163WN1003X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Nutrition Support"
  },
  "163WX0002X": {
    "taxonomy_code": "163WX0002X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Obstetric, High-Risk"
  },
  "163WX0003X": {
    "taxonomy_code": "163WX0003X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Obstetric, Inpatient"
  },
  "163WX0106X": {
    "taxonomy_code": "163WX0106X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Occupational Health"
  },
  "163WX0200X": {
    "taxonomy_code": "163WX0200X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Oncology"
  },
  "163WX1100X": {
    "taxonomy_code": "163WX1100X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Ophthalmic"
  },
  "163WX0800X": {
    "taxonomy_code": "163WX0800X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Orthopedic"
  },
  "163WX1500X": {
    "taxonomy_code": "163WX1500X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Ostomy Care"
  },
  "163WX0601X": {
    "taxonomy_code": "163WX0601X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Otorhinolaryngology & Head-Neck"
  },
  "163WP0000X": {
    "taxonomy_code": "163WP0000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Pain Management"
  },
  "163WP0218X": {
    "taxonomy_code": "163WP0218X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Pediatric Oncology"
  },
  "163WP0200X": {
    "taxonomy_code": "163WP0200X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Pediatrics"
  },
  "163WP1700X": {
    "taxonomy_code": "163WP1700X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Perinatal"
  },
  "163WS0121X": {
    "taxonomy_code": "163WS0121X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Plastic Surgery"
  },
  "163WP0808X": {
    "taxonomy_code": "163WP0808X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Psychiatric/Mental Health"
  },
  "163WP0809X": {
    "taxonomy_code": "163WP0809X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Psychiatric/Mental Health, Adult"
  },
  "163WP0807X": {
    "taxonomy_code": "163WP0807X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Psychiatric/Mental Health, Child & Adolescent"
  },
  "163WR0006X": {
    "taxonomy_code": "163WR0006X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Registered Nurse First Assistant"
  },
  "163WR0400X": {
    "taxonomy_code": "163WR0400X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Rehabilitation"
  },
  "163WR1000X": {
    "taxonomy_code": "163WR1000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Reproductive Endocrinology/Infertility"
  },
  "163WS0200X": {
    "taxonomy_code": "163WS0200X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "School"
  },
  "163WU0100X": {
    "taxonomy_code": "163WU0100X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Urology"
  },
  "163WW0101X": {
    "taxonomy_code": "163WW0101X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Women's Health Care, Ambulatory"
  },
  "163WW0000X": {
    "taxonomy_code": "163WW0000X",
    "role": "",
    "specialty": "Registered Nurse",
    "sub_specialty": "Wound Care"
  },
  "372600000X": {
    "taxonomy_code": "372600000X",
    "role": "",
    "specialty": "Adult Companion",
    "sub_specialty": ""
  },
  "372500000X": {
    "taxonomy_code": "372500000X",
    "role": "",
    "specialty": "Chore Provider",
    "sub_specialty": ""
  },
  "373H00000X": {
    "taxonomy_code": "373H00000X",
    "role": "",
    "specialty": "Day Training/Habilitation Specialist",
    "sub_specialty": ""
  },
  "374J00000X": {
    "taxonomy_code": "374J00000X",
    "role": "",
    "specialty": "Doula",
    "sub_specialty": ""
  },
  "374U00000X": {
    "taxonomy_code": "374U00000X",
    "role": "",
    "specialty": "Home Health Aide",
    "sub_specialty": ""
  },
  "376J00000X": {
    "taxonomy_code": "376J00000X",
    "role": "",
    "specialty": "Homemaker",
    "sub_specialty": ""
  },
  "376K00000X": {
    "taxonomy_code": "376K00000X",
    "role": "",
    "specialty": "Nurse's Aide",
    "sub_specialty": ""
  },
  "376G00000X": {
    "taxonomy_code": "376G00000X",
    "role": "",
    "specialty": "Nursing Home Administrator",
    "sub_specialty": ""
  },
  "374T00000X": {
    "taxonomy_code": "374T00000X",
    "role": "",
    "specialty": "Religious Nonmedical Nursing Personnel",
    "sub_specialty": ""
  },
  "374K00000X": {
    "taxonomy_code": "374K00000X",
    "role": "",
    "specialty": "Religious Nonmedical Practitioner",
    "sub_specialty": ""
  },
  "374700000X": {
    "taxonomy_code": "374700000X",
    "role": "",
    "specialty": "Technician",
    "sub_specialty": ""
  },
  "3747A0650X": {
    "taxonomy_code": "3747A0650X",
    "role": "",
    "specialty": "Technician",
    "sub_specialty": "Attendant Care Provider"
  },
  "3747P1801X": {
    "taxonomy_code": "3747P1801X",
    "role": "",
    "specialty": "Technician",
    "sub_specialty": "Personal Care Attendant"
  },
  "171100000X": {
    "taxonomy_code": "171100000X",
    "role": "",
    "specialty": "Acupuncturist",
    "sub_specialty": ""
  },
  "171M00000X": {
    "taxonomy_code": "171M00000X",

In [18]:
import json

# Read the file with utf-8-sig to handle BOM
with open('/Users/tomcraig/dev/ETL/WinnowPackages/Aya.Winnow.Domain.Model/Taxonomies/taxonomycodes.json', 'r', encoding='utf-8-sig') as f:
    content = f.read()

# Load as JSON
updated_taxonomy = json.loads(content)
print(f"Loaded {len(updated_taxonomy)} entries from taxonomycodes.json")
print(json.dumps(updated_taxonomy, indent=2))

Loaded 863 entries from taxonomycodes.json
{
  "2086S0129X": {
    "taxonomy_code": "2086S0129X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Vascular Surgery"
  },
  "207RN0300X": {
    "taxonomy_code": "207RN0300X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Nephrology"
  },
  "207NI0002X": {
    "taxonomy_code": "207NI0002X",
    "role": "Physician",
    "specialty": "Dermatology",
    "sub_specialty": "Clinical & Laboratory Dermatological Immunology"
  },
  "152WL0500X": {
    "taxonomy_code": "152WL0500X",
    "role": "Physician",
    "specialty": "Optometrist",
    "sub_specialty": "Low Vision Rehabilitation"
  },
  "207RA0401X": {
    "taxonomy_code": "207RA0401X",
    "role": "Physician",
    "specialty": "Addiction Medicine",
    "sub_specialty": "Addiction Medicine"
  },
  "204D00000X": {
    "taxonomy_code": "204D00000X",
    "role": "Physician",
    "specialty": "Neuromusculoskeletal Medicine & OMM",
    "sub_specialty": "Neuromusculoskeletal Medicine & OMM"
  },
  "103TB0200X": {
    "taxonomy_code": "103TB0200X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Cognitive & Behavioral"
  },
  "207ZP0104X": {
    "taxonomy_code": "207ZP0104X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Chemical Pathology"
  },
  "364SX0204X": {
    "taxonomy_code": "364SX0204X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Oncology, Pediatrics"
  },
  "152WX0102X": {
    "taxonomy_code": "152WX0102X",
    "role": "Physician",
    "specialty": "Optometrist",
    "sub_specialty": "Occupational Vision"
  },
  "2086S0122X": {
    "taxonomy_code": "2086S0122X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Plastic and Reconstructive Surgery"
  },
  "364SR0400X": {
    "taxonomy_code": "364SR0400X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Rehabilitation"
  },
  "207QA0000X": {
    "taxonomy_code": "207QA0000X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Adolescent Medicine"
  },
  "207ND0101X": {
    "taxonomy_code": "207ND0101X",
    "role": "Physician",
    "specialty": "Dermatology",
    "sub_specialty": "MOHS-Micrographic Surgery"
  },
  "207PH0002X": {
    "taxonomy_code": "207PH0002X",
    "role": "Physician",
    "specialty": "Hospice and Palliative Medicine",
    "sub_specialty": "Emergency Medicine"
  },
  "364SF0001X": {
    "taxonomy_code": "364SF0001X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Family Health"
  },
  "364SP1700X": {
    "taxonomy_code": "364SP1700X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Perinatal"
  },
  "2083T0002X": {
    "taxonomy_code": "2083T0002X",
    "role": "Physician",
    "specialty": "Preventive Medicine",
    "sub_specialty": "Medical Toxicology"
  },
  "207SG0201X": {
    "taxonomy_code": "207SG0201X",
    "role": "Physician",
    "specialty": "Clinical Genetics",
    "sub_specialty": "Clinical Genetics (M.D.)"
  },
  "207R00000X": {
    "taxonomy_code": "207R00000X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Internal Medicine"
  },
  "133VN1401X": {
    "taxonomy_code": "133VN1401X",
    "role": "Diet & Nutrition",
    "specialty": "Dietician, Registered",
    "sub_specialty": "Pediatric Critical Care Nutrition"
  },
  "207UN0903X": {
    "taxonomy_code": "207UN0903X",
    "role": "Physician",
    "specialty": "Nuclear Medicine",
    "sub_specialty": "In Vivo & In Vitro Nuclear Medicine"
  },
  "2080T0002X": {
    "taxonomy_code": "2080T0002X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Medical Toxicology"
  },
  "2084B0002X": {
    "taxonomy_code": "2084B0002X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Bariatric Medicine"
  },
  "111NR0400X": {
    "taxonomy_code": "111NR0400X",
    "role": "Physician",
    "specialty": "Chiropractor",
    "sub_specialty": "Rehabilitation"
  },
  "2251H1300X": {
    "taxonomy_code": "2251H1300X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Human Factors"
  },
  "207RA0002X": {
    "taxonomy_code": "207RA0002X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Adult Congenital Heart Disease"
  },
  "2084F0202X": {
    "taxonomy_code": "2084F0202X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Forensic Psychiatry"
  },
  "208M00000X": {
    "taxonomy_code": "208M00000X",
    "role": "Physician",
    "specialty": "Hospitalist",
    "sub_specialty": "Hospitalist"
  },
  "2080P0008X": {
    "taxonomy_code": "2080P0008X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Neurodevelopmental Disabilities"
  },
  "364SL0600X": {
    "taxonomy_code": "364SL0600X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Long-term Care"
  },
  "367H00000X": {
    "taxonomy_code": "367H00000X",
    "role": "Nurses",
    "specialty": "Anesthesiologist Assistant",
    "sub_specialty": "Anesthesiologist Assistant"
  },
  "207ZI0100X": {
    "taxonomy_code": "207ZI0100X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Immunopathology"
  },
  "207QB0002X": {
    "taxonomy_code": "207QB0002X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Bariatric Medicine"
  },
  "2251X0800X": {
    "taxonomy_code": "2251X0800X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Orthopedic"
  },
  "2082S0105X": {
    "taxonomy_code": "2082S0105X",
    "role": "Physician",
    "specialty": "Surgery, Plastic",
    "sub_specialty": "Surgery of the Hand"
  },
  "207RH0003X": {
    "taxonomy_code": "207RH0003X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Hematology & Oncology"
  },
  "363A00000X": {
    "taxonomy_code": "363A00000X",
    "role": "Physician Assistant",
    "specialty": "Physician Assistant",
    "sub_specialty": "Physician Assistant"
  },
  "207RG0100X": {
    "taxonomy_code": "207RG0100X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Gastroenterology"
  },
  "2251P0200X": {
    "taxonomy_code": "2251P0200X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Pediatrics"
  },
  "2083A0300X": {
    "taxonomy_code": "2083A0300X",
    "role": "Physician",
    "specialty": "Addiction Medicine",
    "sub_specialty": "Addiction Medicine"
  },
  "103TF0200X": {
    "taxonomy_code": "103TF0200X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Forensic"
  },
  "207X00000X": {
    "taxonomy_code": "207X00000X",
    "role": "Physician",
    "specialty": "Surgery, Orthopedic",
    "sub_specialty": "Surgery, Orthopedic"
  },
  "213ER0200X": {
    "taxonomy_code": "213ER0200X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Radiology"
  },
  "163WC3500X": {
    "taxonomy_code": "163WC3500X",
    "role": "Nurses",
    "specialty": "Registered Nurse",
    "sub_specialty": "Cardiac Rehabilitation"
  },
  "103TC0700X": {
    "taxonomy_code": "103TC0700X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Clinical"
  },
  "207RA0001X": {
    "taxonomy_code": "207RA0001X",
    "role": "Physician",
    "specialty": "Advanced Heart Failure and Transplant Cardiology",
    "sub_specialty": "Advanced Heart Failure and Transplant Cardiology"
  },
  "363LC1500X": {
    "taxonomy_code": "363LC1500X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Community Health"
  },
  "231H00000X": {
    "taxonomy_code": "231H00000X",
    "role": "Physician",
    "specialty": "Audiologist",
    "sub_specialty": "Audiologist"
  },
  "207RI0008X": {
    "taxonomy_code": "207RI0008X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Hepatology"
  },
  "225XL0004X": {
    "taxonomy_code": "225XL0004X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Low Vision"
  },
  "363LA2100X": {
    "taxonomy_code": "363LA2100X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Acute Care"
  },
  "2086H0002X": {
    "taxonomy_code": "2086H0002X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Hospice and Palliative Medicine"
  },
  "207ZH0000X": {
    "taxonomy_code": "207ZH0000X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Hematology"
  },
  "207RX0202X": {
    "taxonomy_code": "207RX0202X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Medical Oncology"
  },
  "2251S0007X": {
    "taxonomy_code": "2251S0007X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Sports"
  },
  "207Q00000X": {
    "taxonomy_code": "207Q00000X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Family Medicine"
  },
  "106S00000X": {
    "taxonomy_code": "106S00000X",
    "role": "Behavioral Health",
    "specialty": "Technician",
    "sub_specialty": "Technician"
  },
  "364SX0106X": {
    "taxonomy_code": "364SX0106X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Occupational Health"
  },
  "207QA0401X": {
    "taxonomy_code": "207QA0401X",
    "role": "Physician",
    "specialty": "Addiction Medicine",
    "sub_specialty": "Addiction Medicine"
  },
  "208800000X": {
    "taxonomy_code": "208800000X",
    "role": "Physician",
    "specialty": "Urology",
    "sub_specialty": "Urology"
  },
  "213ES0000X": {
    "taxonomy_code": "213ES0000X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Sports Medicine"
  },
  "207QA0505X": {
    "taxonomy_code": "207QA0505X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Adult Medicine"
  },
  "225XP0019X": {
    "taxonomy_code": "225XP0019X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Physical Rehabilitation"
  },
  "103TC1900X": {
    "taxonomy_code": "103TC1900X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Counseling"
  },
  "106E00000X": {
    "taxonomy_code": "106E00000X",
    "role": "Behavioral Health",
    "specialty": "Assistant Behavior Analyst",
    "sub_specialty": "Assistant Behavior Analyst"
  },
  "364SP0811X": {
    "taxonomy_code": "364SP0811X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist, Psychiatric",
    "sub_specialty": "Mental Health, Chronically Ill"
  },
  "207RS0012X": {
    "taxonomy_code": "207RS0012X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Sleep Medicine"
  },
  "2080P0203X": {
    "taxonomy_code": "2080P0203X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Pediatric Critical Care Medicine"
  },
  "207RR0500X": {
    "taxonomy_code": "207RR0500X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Rheumatology"
  },
  "207RB0002X": {
    "taxonomy_code": "207RB0002X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Bariatric Medicine"
  },
  "2086S0102X": {
    "taxonomy_code": "2086S0102X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Surgical Critical Care"
  },
  "207YX0905X": {
    "taxonomy_code": "207YX0905X",
    "role": "Physician",
    "specialty": "Otolaryngology",
    "sub_specialty": "Otolaryngology"
  },
  "207VX0000X": {
    "taxonomy_code": "207VX0000X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Obstetrics"
  },
  "103TA0700X": {
    "taxonomy_code": "103TA0700X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Adult Development & Aging"
  },
  "207P00000X": {
    "taxonomy_code": "207P00000X",
    "role": "Physician",
    "specialty": "Emergency Medicine",
    "sub_specialty": "Emergency Medicine"
  },
  "103TR0400X": {
    "taxonomy_code": "103TR0400X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Rehabilitation"
  },
  "208D00000X": {
    "taxonomy_code": "208D00000X",
    "role": "Physician",
    "specialty": "General Practice",
    "sub_specialty": "General Practice"
  },
  "2084P0800X": {
    "taxonomy_code": "2084P0800X",
    "role": "Physician",
    "specialty": "Psychiatry",
    "sub_specialty": "Psychiatry"
  },
  "225XN1300X": {
    "taxonomy_code": "225XN1300X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Neurorehabilitation"
  },
  "2085P0229X": {
    "taxonomy_code": "2085P0229X",
    "role": "Physician",
    "specialty": "Radiology",
    "sub_specialty": "Pediatric Radiology"
  },
  "2081N0008X": {
    "taxonomy_code": "2081N0008X",
    "role": "Physician",
    "specialty": "Physical Medicine & Rehabilitation",
    "sub_specialty": "Neuromuscular Medicine"
  },
  "207RG0300X": {
    "taxonomy_code": "207RG0300X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Geriatric Medicine"
  },
  "213EG0000X": {
    "taxonomy_code": "213EG0000X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "General Practice"
  },
  "208200000X": {
    "taxonomy_code": "208200000X",
    "role": "Physician",
    "specialty": "Surgery, Plastic",
    "sub_specialty": "Surgery, Plastic"
  },
  "2084P0802X": {
    "taxonomy_code": "2084P0802X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Addiction Psychiatry"
  },
  "207YS0123X": {
    "taxonomy_code": "207YS0123X",
    "role": "Physician",
    "specialty": "Otolaryngology",
    "sub_specialty": "Facial Plastic Surgery"
  },
  "363LP1700X": {
    "taxonomy_code": "363LP1700X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Perinatal"
  },
  "364SP0809X": {
    "taxonomy_code": "364SP0809X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist, Psychiatric",
    "sub_specialty": "Mental Health, Adult"
  },
  "2083P0500X": {
    "taxonomy_code": "2083P0500X",
    "role": "Physician",
    "specialty": "Preventive Medicine",
    "sub_specialty": "Occupational Environmental Medicine"
  },
  "2084S0010X": {
    "taxonomy_code": "2084S0010X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Sports Medicine"
  },
  "207VX0201X": {
    "taxonomy_code": "207VX0201X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Gynecologic Oncology"
  },
  "2084P0005X": {
    "taxonomy_code": "2084P0005X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Neurodevelopmental Disabilities"
  },
  "225XE0001X": {
    "taxonomy_code": "225XE0001X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Environmental Modification"
  },
  "207RS0010X": {
    "taxonomy_code": "207RS0010X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Sports Medicine"
  },
  "207YP0228X": {
    "taxonomy_code": "207YP0228X",
    "role": "Physician",
    "specialty": "Otolaryngology",
    "sub_specialty": "Pediatric Otolaryngology"
  },
  "103TH0004X": {
    "taxonomy_code": "103TH0004X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Health"
  },
  "103TM1800X": {
    "taxonomy_code": "103TM1800X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Intellectual & Developmental Disabilities"
  },
  "207XP3100X": {
    "taxonomy_code": "207XP3100X",
    "role": "Physician",
    "specialty": "Surgery, Orthopedic",
    "sub_specialty": "Pediatric Orthopedic Surgery"
  },
  "207VF0040X": {
    "taxonomy_code": "207VF0040X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Female Pelvic Medicine and Reconstructive Surgery"
  },
  "208600000X": {
    "taxonomy_code": "208600000X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Surgery"
  },
  "207VG0400X": {
    "taxonomy_code": "207VG0400X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Gynecology"
  },
  "363LS0200X": {
    "taxonomy_code": "363LS0200X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "School"
  },
  "2080P0210X": {
    "taxonomy_code": "2080P0210X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Pediatric Nephrology"
  },
  "103T00000X": {
    "taxonomy_code": "103T00000X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Psychologist"
  },
  "103TP0016X": {
    "taxonomy_code": "103TP0016X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Prescribing (Medical)"
  },
  "2084N0402X": {
    "taxonomy_code": "2084N0402X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Child Neurology"
  },
  "207RC0200X": {
    "taxonomy_code": "207RC0200X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Critical Care Medicine"
  },
  "213EP0504X": {
    "taxonomy_code": "213EP0504X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Public Medicine"
  },
  "225100000X": {
    "taxonomy_code": "225100000X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Physical Therapist"
  },
  "208C00000X": {
    "taxonomy_code": "208C00000X",
    "role": "Physician",
    "specialty": "Surgery, Colon & Rectal",
    "sub_specialty": "Surgery, Colon & Rectal"
  },
  "213EP1101X": {
    "taxonomy_code": "213EP1101X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Primary Podiatric Medicine"
  },
  "2080A0000X": {
    "taxonomy_code": "2080A0000X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Adolescent Medicine"
  },
  "363LX0106X": {
    "taxonomy_code": "363LX0106X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Occupational Health"
  },
  "204C00000X": {
    "taxonomy_code": "204C00000X",
    "role": "Physician",
    "specialty": "Neuromusculoskeletal Medicine",
    "sub_specialty": "Sports Medicine"
  },
  "231HA2500X": {
    "taxonomy_code": "231HA2500X",
    "role": "Physician",
    "specialty": "Audiologist",
    "sub_specialty": "Assistive Technology Supplier"
  },
  "2084P2900X": {
    "taxonomy_code": "2084P2900X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Pain Medicine"
  },
  "2081P0004X": {
    "taxonomy_code": "2081P0004X",
    "role": "Physician",
    "specialty": "Physical Medicine & Rehabilitation",
    "sub_specialty": "Spinal Cord Injury Medicine"
  },
  "2086S0120X": {
    "taxonomy_code": "2086S0120X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Pediatric Surgery"
  },
  "364SN0800X": {
    "taxonomy_code": "364SN0800X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Neuroscience"
  },
  "207ZB0001X": {
    "taxonomy_code": "207ZB0001X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Blood Banking & Transfusion Medicine"
  },

In [17]:
# Fill empty sub_specialty with specialty value
original_count = len(updated_taxonomy)
print(f"Starting with {original_count} entries")

for code, entry in updated_taxonomy.items():
    if not entry.get("sub_specialty") or entry["sub_specialty"].strip() == "":
        entry["sub_specialty"] = entry.get("specialty", "")

final_count = len(updated_taxonomy)
print(f"After update: {final_count} entries")
print(f"Entries preserved: {final_count == original_count}")

print(json.dumps(updated_taxonomy, indent=2))

Starting with 863 entries
After update: 863 entries
Entries preserved: True
{
  "2086S0129X": {
    "taxonomy_code": "2086S0129X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Vascular Surgery"
  },
  "207RN0300X": {
    "taxonomy_code": "207RN0300X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Nephrology"
  },
  "207NI0002X": {
    "taxonomy_code": "207NI0002X",
    "role": "Physician",
    "specialty": "Dermatology",
    "sub_specialty": "Clinical & Laboratory Dermatological Immunology"
  },
  "152WL0500X": {
    "taxonomy_code": "152WL0500X",
    "role": "Physician",
    "specialty": "Optometrist",
    "sub_specialty": "Low Vision Rehabilitation"
  },
  "207RA0401X": {
    "taxonomy_code": "207RA0401X",
    "role": "Physician",
    "specialty": "Addiction Medicine",
    "sub_specialty": "Addiction Medicine"
  },
  "204D00000X": {
    "taxonomy_code": "204D00000X",
    "role": "Physician",
    "specialty": "Neuromusculoskeletal Medicine & OMM",
    "sub_specialty": "Neuromusculoskeletal Medicine & OMM"
  },
  "103TB0200X": {
    "taxonomy_code": "103TB0200X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Cognitive & Behavioral"
  },
  "207ZP0104X": {
    "taxonomy_code": "207ZP0104X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Chemical Pathology"
  },
  "364SX0204X": {
    "taxonomy_code": "364SX0204X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Oncology, Pediatrics"
  },
  "152WX0102X": {
    "taxonomy_code": "152WX0102X",
    "role": "Physician",
    "specialty": "Optometrist",
    "sub_specialty": "Occupational Vision"
  },
  "2086S0122X": {
    "taxonomy_code": "2086S0122X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Plastic and Reconstructive Surgery"
  },
  "364SR0400X": {
    "taxonomy_code": "364SR0400X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Rehabilitation"
  },
  "207QA0000X": {
    "taxonomy_code": "207QA0000X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Adolescent Medicine"
  },
  "207ND0101X": {
    "taxonomy_code": "207ND0101X",
    "role": "Physician",
    "specialty": "Dermatology",
    "sub_specialty": "MOHS-Micrographic Surgery"
  },
  "207PH0002X": {
    "taxonomy_code": "207PH0002X",
    "role": "Physician",
    "specialty": "Hospice and Palliative Medicine",
    "sub_specialty": "Emergency Medicine"
  },
  "364SF0001X": {
    "taxonomy_code": "364SF0001X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Family Health"
  },
  "364SP1700X": {
    "taxonomy_code": "364SP1700X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Perinatal"
  },
  "2083T0002X": {
    "taxonomy_code": "2083T0002X",
    "role": "Physician",
    "specialty": "Preventive Medicine",
    "sub_specialty": "Medical Toxicology"
  },
  "207SG0201X": {
    "taxonomy_code": "207SG0201X",
    "role": "Physician",
    "specialty": "Clinical Genetics",
    "sub_specialty": "Clinical Genetics (M.D.)"
  },
  "207R00000X": {
    "taxonomy_code": "207R00000X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Internal Medicine"
  },
  "133VN1401X": {
    "taxonomy_code": "133VN1401X",
    "role": "Diet & Nutrition",
    "specialty": "Dietician, Registered",
    "sub_specialty": "Pediatric Critical Care Nutrition"
  },
  "207UN0903X": {
    "taxonomy_code": "207UN0903X",
    "role": "Physician",
    "specialty": "Nuclear Medicine",
    "sub_specialty": "In Vivo & In Vitro Nuclear Medicine"
  },
  "2080T0002X": {
    "taxonomy_code": "2080T0002X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Medical Toxicology"
  },
  "2084B0002X": {
    "taxonomy_code": "2084B0002X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Bariatric Medicine"
  },
  "111NR0400X": {
    "taxonomy_code": "111NR0400X",
    "role": "Physician",
    "specialty": "Chiropractor",
    "sub_specialty": "Rehabilitation"
  },
  "2251H1300X": {
    "taxonomy_code": "2251H1300X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Human Factors"
  },
  "207RA0002X": {
    "taxonomy_code": "207RA0002X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Adult Congenital Heart Disease"
  },
  "2084F0202X": {
    "taxonomy_code": "2084F0202X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Forensic Psychiatry"
  },
  "208M00000X": {
    "taxonomy_code": "208M00000X",
    "role": "Physician",
    "specialty": "Hospitalist",
    "sub_specialty": "Hospitalist"
  },
  "2080P0008X": {
    "taxonomy_code": "2080P0008X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Neurodevelopmental Disabilities"
  },
  "364SL0600X": {
    "taxonomy_code": "364SL0600X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Long-term Care"
  },
  "367H00000X": {
    "taxonomy_code": "367H00000X",
    "role": "Nurses",
    "specialty": "Anesthesiologist Assistant",
    "sub_specialty": "Anesthesiologist Assistant"
  },
  "207ZI0100X": {
    "taxonomy_code": "207ZI0100X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Immunopathology"
  },
  "207QB0002X": {
    "taxonomy_code": "207QB0002X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Bariatric Medicine"
  },
  "2251X0800X": {
    "taxonomy_code": "2251X0800X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Orthopedic"
  },
  "2082S0105X": {
    "taxonomy_code": "2082S0105X",
    "role": "Physician",
    "specialty": "Surgery, Plastic",
    "sub_specialty": "Surgery of the Hand"
  },
  "207RH0003X": {
    "taxonomy_code": "207RH0003X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Hematology & Oncology"
  },
  "363A00000X": {
    "taxonomy_code": "363A00000X",
    "role": "Physician Assistant",
    "specialty": "Physician Assistant",
    "sub_specialty": "Physician Assistant"
  },
  "207RG0100X": {
    "taxonomy_code": "207RG0100X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Gastroenterology"
  },
  "2251P0200X": {
    "taxonomy_code": "2251P0200X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Pediatrics"
  },
  "2083A0300X": {
    "taxonomy_code": "2083A0300X",
    "role": "Physician",
    "specialty": "Addiction Medicine",
    "sub_specialty": "Addiction Medicine"
  },
  "103TF0200X": {
    "taxonomy_code": "103TF0200X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Forensic"
  },
  "207X00000X": {
    "taxonomy_code": "207X00000X",
    "role": "Physician",
    "specialty": "Surgery, Orthopedic",
    "sub_specialty": "Surgery, Orthopedic"
  },
  "213ER0200X": {
    "taxonomy_code": "213ER0200X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Radiology"
  },
  "163WC3500X": {
    "taxonomy_code": "163WC3500X",
    "role": "Nurses",
    "specialty": "Registered Nurse",
    "sub_specialty": "Cardiac Rehabilitation"
  },
  "103TC0700X": {
    "taxonomy_code": "103TC0700X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Clinical"
  },
  "207RA0001X": {
    "taxonomy_code": "207RA0001X",
    "role": "Physician",
    "specialty": "Advanced Heart Failure and Transplant Cardiology",
    "sub_specialty": "Advanced Heart Failure and Transplant Cardiology"
  },
  "363LC1500X": {
    "taxonomy_code": "363LC1500X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Community Health"
  },
  "231H00000X": {
    "taxonomy_code": "231H00000X",
    "role": "Physician",
    "specialty": "Audiologist",
    "sub_specialty": "Audiologist"
  },
  "207RI0008X": {
    "taxonomy_code": "207RI0008X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Hepatology"
  },
  "225XL0004X": {
    "taxonomy_code": "225XL0004X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Low Vision"
  },
  "363LA2100X": {
    "taxonomy_code": "363LA2100X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Acute Care"
  },
  "2086H0002X": {
    "taxonomy_code": "2086H0002X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Hospice and Palliative Medicine"
  },
  "207ZH0000X": {
    "taxonomy_code": "207ZH0000X",
    "role": "Physician",
    "specialty": "Pathology",
    "sub_specialty": "Hematology"
  },
  "207RX0202X": {
    "taxonomy_code": "207RX0202X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Medical Oncology"
  },
  "2251S0007X": {
    "taxonomy_code": "2251S0007X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Sports"
  },
  "207Q00000X": {
    "taxonomy_code": "207Q00000X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Family Medicine"
  },
  "106S00000X": {
    "taxonomy_code": "106S00000X",
    "role": "Behavioral Health",
    "specialty": "Technician",
    "sub_specialty": "Technician"
  },
  "364SX0106X": {
    "taxonomy_code": "364SX0106X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Occupational Health"
  },
  "207QA0401X": {
    "taxonomy_code": "207QA0401X",
    "role": "Physician",
    "specialty": "Addiction Medicine",
    "sub_specialty": "Addiction Medicine"
  },
  "208800000X": {
    "taxonomy_code": "208800000X",
    "role": "Physician",
    "specialty": "Urology",
    "sub_specialty": "Urology"
  },
  "213ES0000X": {
    "taxonomy_code": "213ES0000X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Sports Medicine"
  },
  "207QA0505X": {
    "taxonomy_code": "207QA0505X",
    "role": "Physician",
    "specialty": "Family Medicine",
    "sub_specialty": "Adult Medicine"
  },
  "225XP0019X": {
    "taxonomy_code": "225XP0019X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Physical Rehabilitation"
  },
  "103TC1900X": {
    "taxonomy_code": "103TC1900X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Counseling"
  },
  "106E00000X": {
    "taxonomy_code": "106E00000X",
    "role": "Behavioral Health",
    "specialty": "Assistant Behavior Analyst",
    "sub_specialty": "Assistant Behavior Analyst"
  },
  "364SP0811X": {
    "taxonomy_code": "364SP0811X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist, Psychiatric",
    "sub_specialty": "Mental Health, Chronically Ill"
  },
  "207RS0012X": {
    "taxonomy_code": "207RS0012X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Sleep Medicine"
  },
  "2080P0203X": {
    "taxonomy_code": "2080P0203X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Pediatric Critical Care Medicine"
  },
  "207RR0500X": {
    "taxonomy_code": "207RR0500X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Rheumatology"
  },
  "207RB0002X": {
    "taxonomy_code": "207RB0002X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Bariatric Medicine"
  },
  "2086S0102X": {
    "taxonomy_code": "2086S0102X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Surgical Critical Care"
  },
  "207YX0905X": {
    "taxonomy_code": "207YX0905X",
    "role": "Physician",
    "specialty": "Otolaryngology",
    "sub_specialty": "Otolaryngology"
  },
  "207VX0000X": {
    "taxonomy_code": "207VX0000X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Obstetrics"
  },
  "103TA0700X": {
    "taxonomy_code": "103TA0700X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Adult Development & Aging"
  },
  "207P00000X": {
    "taxonomy_code": "207P00000X",
    "role": "Physician",
    "specialty": "Emergency Medicine",
    "sub_specialty": "Emergency Medicine"
  },
  "103TR0400X": {
    "taxonomy_code": "103TR0400X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Rehabilitation"
  },
  "208D00000X": {
    "taxonomy_code": "208D00000X",
    "role": "Physician",
    "specialty": "General Practice",
    "sub_specialty": "General Practice"
  },
  "2084P0800X": {
    "taxonomy_code": "2084P0800X",
    "role": "Physician",
    "specialty": "Psychiatry",
    "sub_specialty": "Psychiatry"
  },
  "225XN1300X": {
    "taxonomy_code": "225XN1300X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Neurorehabilitation"
  },
  "2085P0229X": {
    "taxonomy_code": "2085P0229X",
    "role": "Physician",
    "specialty": "Radiology",
    "sub_specialty": "Pediatric Radiology"
  },
  "2081N0008X": {
    "taxonomy_code": "2081N0008X",
    "role": "Physician",
    "specialty": "Physical Medicine & Rehabilitation",
    "sub_specialty": "Neuromuscular Medicine"
  },
  "207RG0300X": {
    "taxonomy_code": "207RG0300X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Geriatric Medicine"
  },
  "213EG0000X": {
    "taxonomy_code": "213EG0000X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "General Practice"
  },
  "208200000X": {
    "taxonomy_code": "208200000X",
    "role": "Physician",
    "specialty": "Surgery, Plastic",
    "sub_specialty": "Surgery, Plastic"
  },
  "2084P0802X": {
    "taxonomy_code": "2084P0802X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Addiction Psychiatry"
  },
  "207YS0123X": {
    "taxonomy_code": "207YS0123X",
    "role": "Physician",
    "specialty": "Otolaryngology",
    "sub_specialty": "Facial Plastic Surgery"
  },
  "363LP1700X": {
    "taxonomy_code": "363LP1700X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Perinatal"
  },
  "364SP0809X": {
    "taxonomy_code": "364SP0809X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist, Psychiatric",
    "sub_specialty": "Mental Health, Adult"
  },
  "2083P0500X": {
    "taxonomy_code": "2083P0500X",
    "role": "Physician",
    "specialty": "Preventive Medicine",
    "sub_specialty": "Occupational Environmental Medicine"
  },
  "2084S0010X": {
    "taxonomy_code": "2084S0010X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Sports Medicine"
  },
  "207VX0201X": {
    "taxonomy_code": "207VX0201X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Gynecologic Oncology"
  },
  "2084P0005X": {
    "taxonomy_code": "2084P0005X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Neurodevelopmental Disabilities"
  },
  "225XE0001X": {
    "taxonomy_code": "225XE0001X",
    "role": "Therapist",
    "specialty": "Occupational Therapist",
    "sub_specialty": "Environmental Modification"
  },
  "207RS0010X": {
    "taxonomy_code": "207RS0010X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Sports Medicine"
  },
  "207YP0228X": {
    "taxonomy_code": "207YP0228X",
    "role": "Physician",
    "specialty": "Otolaryngology",
    "sub_specialty": "Pediatric Otolaryngology"
  },
  "103TH0004X": {
    "taxonomy_code": "103TH0004X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Health"
  },
  "103TM1800X": {
    "taxonomy_code": "103TM1800X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Intellectual & Developmental Disabilities"
  },
  "207XP3100X": {
    "taxonomy_code": "207XP3100X",
    "role": "Physician",
    "specialty": "Surgery, Orthopedic",
    "sub_specialty": "Pediatric Orthopedic Surgery"
  },
  "207VF0040X": {
    "taxonomy_code": "207VF0040X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Female Pelvic Medicine and Reconstructive Surgery"
  },
  "208600000X": {
    "taxonomy_code": "208600000X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Surgery"
  },
  "207VG0400X": {
    "taxonomy_code": "207VG0400X",
    "role": "Physician",
    "specialty": "Obstetrics & Gynecology",
    "sub_specialty": "Gynecology"
  },
  "363LS0200X": {
    "taxonomy_code": "363LS0200X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "School"
  },
  "2080P0210X": {
    "taxonomy_code": "2080P0210X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Pediatric Nephrology"
  },
  "103T00000X": {
    "taxonomy_code": "103T00000X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Psychologist"
  },
  "103TP0016X": {
    "taxonomy_code": "103TP0016X",
    "role": "Behavioral Health",
    "specialty": "Psychologist",
    "sub_specialty": "Prescribing (Medical)"
  },
  "2084N0402X": {
    "taxonomy_code": "2084N0402X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Child Neurology"
  },
  "207RC0200X": {
    "taxonomy_code": "207RC0200X",
    "role": "Physician",
    "specialty": "Internal Medicine",
    "sub_specialty": "Critical Care Medicine"
  },
  "213EP0504X": {
    "taxonomy_code": "213EP0504X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Public Medicine"
  },
  "225100000X": {
    "taxonomy_code": "225100000X",
    "role": "Therapist",
    "specialty": "Physical Therapist",
    "sub_specialty": "Physical Therapist"
  },
  "208C00000X": {
    "taxonomy_code": "208C00000X",
    "role": "Physician",
    "specialty": "Surgery, Colon & Rectal",
    "sub_specialty": "Surgery, Colon & Rectal"
  },
  "213EP1101X": {
    "taxonomy_code": "213EP1101X",
    "role": "Physician",
    "specialty": "Podiatrist",
    "sub_specialty": "Primary Podiatric Medicine"
  },
  "2080A0000X": {
    "taxonomy_code": "2080A0000X",
    "role": "Physician",
    "specialty": "Pediatrics",
    "sub_specialty": "Adolescent Medicine"
  },
  "363LX0106X": {
    "taxonomy_code": "363LX0106X",
    "role": "Nurses",
    "specialty": "Nurse Practitioner",
    "sub_specialty": "Occupational Health"
  },
  "204C00000X": {
    "taxonomy_code": "204C00000X",
    "role": "Physician",
    "specialty": "Neuromusculoskeletal Medicine",
    "sub_specialty": "Sports Medicine"
  },
  "231HA2500X": {
    "taxonomy_code": "231HA2500X",
    "role": "Physician",
    "specialty": "Audiologist",
    "sub_specialty": "Assistive Technology Supplier"
  },
  "2084P2900X": {
    "taxonomy_code": "2084P2900X",
    "role": "Physician",
    "specialty": "Psychiatry & Neurology",
    "sub_specialty": "Pain Medicine"
  },
  "2081P0004X": {
    "taxonomy_code": "2081P0004X",
    "role": "Physician",
    "specialty": "Physical Medicine & Rehabilitation",
    "sub_specialty": "Spinal Cord Injury Medicine"
  },
  "2086S0120X": {
    "taxonomy_code": "2086S0120X",
    "role": "Physician",
    "specialty": "Surgery",
    "sub_specialty": "Pediatric Surgery"
  },
  "364SN0800X": {
    "taxonomy_code": "364SN0800X",
    "role": "Nurses",
    "specialty": "Clinical Nurse Specialist",
    "sub_specialty": "Neuroscience"
  },
  "207ZB0001X": {
    "taxonomy_code": "207ZB0001X",
    "role": "Physician",
    "specialty": "Pathology",